-- =====================================================
-- INSERT statement for content_id: 160f4aad-037b-4bdf-a14c-18c712e9a944
-- Name: #Bin wise Item stock summary#
-- Action: UPDATE
-- Version: 2026011
-- Generated on: 2026-10-06 16:54:20
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '160f4aad-037b-4bdf-a14c-18c712e9a944', 0, 0,
    NULL, '#Bin wise Item stock summary#', 'This Report will show bin wise available stock quantity.',
    '<report>
  <main>
    <id>160f4aad-037b-4bdf-a14c-18c712e9a944</id>
    <report_name>#Bin wise Item stock summary#</report_name>
    <folder_name>Inventory\Status</folder_name>
    <folder_id>2d9354a7-390e-4346-96db-7deb71635fa1</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Standard</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>Letter</page_size>
    <page_orientation>Landscape</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This Report will show bin wise available stock quantity.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>False</show_interactive_sorts>
    <allow_column_hide>False</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>-1</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_BIN_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_BATCHSERIAL_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ONHAND_STOCK_BIN_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|03-Composite</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>1084119617</id>
    <cell_text>@ConnOUCode@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1488993033</id>
    <cell_text>=if(@ReportTitle@='''',''Bin wise Item stock summary'',@ReportTitle@)</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>19</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1936342366</id>
    <cell_text>@ReportHeader@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>19</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
    <conditional>
      <formula>if(@ReportHeader@='''',''True'',''False'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1664295622</id>
    <cell_text>Bin No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2100336917</id>
    <cell_text>Seq No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>389634282</id>
    <cell_text>Division</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>995780026</id>
    <cell_text>Section</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1191204550</id>
    <cell_text>Department</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>304211138</id>
    <cell_text>Cat1</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>209281628</id>
    <cell_text>Cat2</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2063768831</id>
    <cell_text>Cat3</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>891288680</id>
    <cell_text>Cat4</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>89275991</id>
    <cell_text>Cat5</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1507201417</id>
    <cell_text>Cat6</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>322911384</id>
    <cell_text>Barcode</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1823963220</id>
    <cell_text>Item Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>848126916</id>
    <cell_text>Batch No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>884576672</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>116424191</id>
    <cell_text>MRP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>636324719</id>
    <cell_text>Total Stock</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>16</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1343774853</id>
    <cell_text>Reserved</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1188935644</id>
    <cell_text>Free Stock</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>18</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>651645873</id>
    <cell_text>=''Site Name : ''&amp;{LV_SITE_01.name}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>17</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>244150948</id>
    <cell_text>LV_BIN_01.bin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>917250669</id>
    <cell_text>LV_BIN_01.sequence_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>False</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1564051665</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1268568266</id>
    <cell_text>LV_ITEM_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>50659077</id>
    <cell_text>LV_ITEM_01.department</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>340035667</id>
    <cell_text>LV_ITEM_01.category1</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1115045991</id>
    <cell_text>LV_ITEM_01.category2</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>50570856</id>
    <cell_text>LV_ITEM_01.category3</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1935020193</id>
    <cell_text>LV_ITEM_01.category4</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>676077710</id>
    <cell_text>LV_ITEM_01.category5</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1867018863</id>
    <cell_text>LV_ITEM_01.category6</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>885011552</id>
    <cell_text>=If({LV_ITEM_01.barcode}='''',{LV_ONHAND_STOCK_BIN_01.icode}, {LV_ITEM_01.barcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1510031176</id>
    <cell_text>LV_ITEM_01.item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>662460782</id>
    <cell_text>LV_ITEM_BATCHSERIAL_01.batch_serial_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>13</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1124392598</id>
    <cell_text>LV_ITEM_01.rsp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1118347554</id>
    <cell_text>LV_ITEM_01.mrp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>793472214</id>
    <cell_text>LV_ONHAND_STOCK_BIN_01.total_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>16</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1935318642</id>
    <cell_text>LV_ONHAND_STOCK_BIN_01.reserved_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>520186173</id>
    <cell_text>LV_ONHAND_STOCK_BIN_01.free_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>18</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>824502289</id>
    <cell_text>@ReportFooter@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>19</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>139343033</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>162575090</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>81789338</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1758067860</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1291430706</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>235769741</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1785066918</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>164522039</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>182375687</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>24299937</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>700699720</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>203085076</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>481321175</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>14</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2085915273</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2100415621</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>226734668</id>
    <cell_text>=''Page : ''&amp;@pageNumber@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_SITE_01.name</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>85</column_width>
  </column>
  <column>
    <column_width>85</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>110</column_width>
  </column>
  <column>
    <column_width>104</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>184</column_width>
  </column>
  <column>
    <column_width>166</column_width>
  </column>
  <column>
    <column_width>88</column_width>
  </column>
  <column>
    <column_width>88</column_width>
  </column>
  <column>
    <column_width>88</column_width>
  </column>
  <column>
    <column_width>88</column_width>
  </column>
  <column>
    <column_width>88</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_ITEM_BATCHSERIAL_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_ITEM_BATCHSERIAL_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_ONHAND_STOCK_BIN_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_ONHAND_STOCK_BIN_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_BIN_01</entity_from_name>
    <entity_to_name>LV_ONHAND_STOCK_BIN_01</entity_to_name>
    <entity_from_id>LV_BIN_01</entity_from_id>
    <entity_to_id>LV_ONHAND_STOCK_BIN_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>invbin_code</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>invbin_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_ONHAND_STOCK_BIN_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_ONHAND_STOCK_BIN_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_SITE_01.name</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_BIN_01.bin_no</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_BIN_01.sequence_no</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.division</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.section</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.department</sort_name>
    <sort_title />
    <order_num>5</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category1</sort_name>
    <sort_title />
    <order_num>6</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category2</sort_name>
    <sort_title />
    <order_num>7</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category3</sort_name>
    <sort_title />
    <order_num>8</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category4</sort_name>
    <sort_title />
    <order_num>9</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category5</sort_name>
    <sort_title />
    <order_num>10</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.category6</sort_name>
    <sort_title />
    <order_num>11</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>=If({LV_ITEM_01.barcode}='''', {LV_ONHAND_STOCK_BIN_01.icode}, {LV_ITEM_01.barcode})</sort_name>
    <sort_title />
    <order_num>12</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.item_name</sort_name>
    <sort_title />
    <order_num>13</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_BATCHSERIAL_01.batch_serial_no</sort_name>
    <sort_title />
    <order_num>14</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_SITE_01.name</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1315822270</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_BIN_01.bin_no</filter_name>
    <order_num>1</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>756428789</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2017-09-15 15:14:32', '3653', '2026-10-06 11:00:29.010082',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026011', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '160f4aad-037b-4bdf-a14c-18c712e9a944', '6d0a3125-672a-4b60-a548-1c3be854e5b8', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026011', 'U'
);
