-- =====================================================
-- INSERT statement for content_id: cef34b25-c480-4866-81f8-697310e9a4f6
-- Name: #Stock Audit Entry#
-- Action: UPDATE
-- Version: 2026011
-- Generated on: 2026-10-05 14:31:44
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    'cef34b25-c480-4866-81f8-697310e9a4f6', 0, 0,
    NULL, '#Stock Audit Entry#', 'This is a Stock Audit Entry Document Report, to be used for document printing purpose. Should be executed from Stock Audit Entry only.',
    '<report>
  <main>
    <id>cef34b25-c480-4866-81f8-697310e9a4f6</id>
    <report_name>#Stock Audit Entry#</report_name>
    <folder_name>Inventory\Documents</folder_name>
    <folder_id>3942da7c-bf44-4c44-8eff-f42cf75a97b2</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>4,1,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This is a Stock Audit Entry Document Report, to be used for document printing purpose. Should be executed from Stock Audit Entry only.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>True</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>-1</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_STKAUDIT_COUNT_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|02-Transaction</category>
  </entity>
  <cell>
    <id>738726035</id>
    <cell_text>@ExecutingSQL@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>911216230</id>
    <cell_text>=If(@PrintLogo@=''Y'', OULogo(), '''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>10164398</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>1</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>265771811</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1896746769</id>
    <cell_text>=If(@ReportTitle@!='''', @ReportTitle@, ''Physical Stock Report'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>494450868</id>
    <cell_text>LV_SITE_01.address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>805741887</id>
    <cell_text>={LV_SITE_01.phone1}&amp;'' ''&amp;{LV_SITE_01.phone2}&amp;'' ''&amp;{LV_SITE_01.phone3}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1810355412</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>19</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>607609555</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>23</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1019427111</id>
    <cell_text>={LV_SITE_01.email1}&amp;If({LV_SITE_01.email1}!='''', '', ''&amp;{LV_SITE_01.email2}, {LV_SITE_01.email2})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>114290921</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>19</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1527659681</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>23</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>747762096</id>
    <cell_text>={LV_SITE_01.website}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1661927977</id>
    <cell_text>CIN No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1095671552</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1050693414</id>
    <cell_text>LV_SITE_01.ou_cin</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>2083993391</id>
    <cell_text>Plan</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>20</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1682100525</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>24</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>124781949</id>
    <cell_text>LV_STKAUDIT_COUNT_01.plan_desc</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1882327374</id>
    <cell_text>GSTIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1106419357</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>46597585</id>
    <cell_text>={LV_SITE_01.gst_identification_no}&amp; ''[''&amp;{LV_SITE_01.gst_state_code}&amp;'' -''&amp;{LV_SITE_01.gst_state_name}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>706081411</id>
    <cell_text>Stock Point</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>20</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1611697607</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>24</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>921868150</id>
    <cell_text>LV_STKAUDIT_COUNT_01.stock_point_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1468304945</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>33</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1118831113</id>
    <cell_text>Group / Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>If(LineNumberWithReset({LV_STKAUDIT_COUNT_01.stkentcode},''header'')=1, ''True'', ''False'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>982255890</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>477355288</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>878403384</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>23</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>895610391</id>
    <cell_text>RSP Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>84359842</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>11</cell_row>
    <cell_col>20</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1968357608</id>
    <cell_text>Plan Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2102922148</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1861785353</id>
    <cell_text>LV_STKAUDIT_COUNT_01.plan_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>650684843</id>
    <cell_text>Entry No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <border_top_width>1</border_top_width>
    <border_left_width>1</border_left_width>
    <border_top_color>#000000</border_top_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>997220078</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>22</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1107174835</id>
    <cell_text>={LV_STKAUDIT_COUNT_01.entry_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>577429925</id>
    <cell_text>Plan Activation Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2053146272</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>717226696</id>
    <cell_text>LV_STKAUDIT_COUNT_01.plan_activation_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>690715025</id>
    <cell_text>Entry Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>16</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>400293268</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>22</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1207390853</id>
    <cell_text>={LV_STKAUDIT_COUNT_01.entry_date}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>23</cell_col>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1139344381</id>
    <cell_text>@ReportHeader@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>26</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1059708897</id>
    <cell_text>Group / Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1696385297</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>383285343</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>633464826</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>23</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2109851366</id>
    <cell_text>RSP Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1201101490</id>
    <cell_text>={LV_ITEM_01.section}&amp;'' - ''&amp;{LV_ITEM_01.department}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <conditional>
      <formula>If(CellValue() = '' - '',''true'',''false'') </formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1269638945</id>
    <cell_text>=LineNumberWithReset({LV_STKAUDIT_COUNT_01.stkentcode}&amp;{LV_ITEM_01.section}&amp;{LV_ITEM_01.department},''Assembly'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>13</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#FFFFFF</foreground_color>
    <conditional>
      <formula>If(CellValue() &gt;1,''true'',''false'') </formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1541643363</id>
    <cell_text>=If({LV_ITEM_01.barcode}='''', {LV_ITEM_01.code}, {LV_ITEM_01.barcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <conditional>
      <formula>If({LV_STKAUDIT_COUNT_01.quantity}=Null(), ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1157902578</id>
    <cell_text>={LV_ITEM_01.category1}&amp;'' ''&amp;{LV_ITEM_01.category2}&amp;'' ''&amp;{LV_ITEM_01.category3}&amp;'' ''&amp;{LV_ITEM_01.category4}&amp;'' ''&amp;{LV_ITEM_01.category5}&amp;'' ''&amp;{LV_ITEM_01.category6}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1552040551</id>
    <cell_text>LV_ITEM_01.mrp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>17</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>685296553</id>
    <cell_text>LV_STKAUDIT_COUNT_01.quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>17</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1691970898</id>
    <cell_text>LV_ITEM_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>17</cell_row>
    <cell_col>23</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1184088241</id>
    <cell_text>={LV_ITEM_01.mrp}*{LV_STKAUDIT_COUNT_01.quantity}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1971010147</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>Or([E19]=''Batch : '',[E19]=''Serial : '')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>543483461</id>
    <cell_text>=If({LV_ITEM_01.item_management_mode}=''B'', ''Batch : ''&amp;{LV_STKAUDIT_COUNT_01.batch_serial_string}, ''Serial : ''&amp;{LV_STKAUDIT_COUNT_01.batch_serial_string})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>29</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1407231993</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>613830808</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>539075810</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>714756258</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1059438825</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>10</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1866508354</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>591294934</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1375001405</id>
    <cell_text>Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>14</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1264120398</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>989531519</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2134172130</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>19</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1431439326</id>
    <cell_text>=AggSum({LV_STKAUDIT_COUNT_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>20</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1613373201</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>23</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>593279316</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2006116746</id>
    <cell_text>=AggSum([Z18])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1717190652</id>
    <cell_text>@ReportFooter@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>22</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>26</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>If(@ReportFooter@=Null(), ''True'', ''False'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1826137905</id>
    <cell_text>=''For ''&amp;@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>760736201</id>
    <cell_text>LV_STKAUDIT_COUNT_01.created_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>26</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1453636666</id>
    <cell_text>Created By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2068983744</id>
    <cell_text>Checked By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>135908859</id>
    <cell_text>Passed By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1225513209</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1096829147</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1010652164</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1590101676</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>12</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1957263488</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>17</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1263359606</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>23</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1765375098</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>31</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>606568873</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1476701504</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2042019014</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1173873412</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>465908516</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2076317776</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>19</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1823593608</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>20</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1921100218</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>21</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1960364432</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>22</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>675124814</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>23</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1092147164</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>360524953</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1516782483</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1204645121</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>27</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1579901310</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>31</cell_row>
    <cell_col>28</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>819035316</id>
    <cell_text>=''Page :  ''&amp;PageNoWithReset({LV_STKAUDIT_COUNT_01.stkentcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>31</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <row_height>4</row_height>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
    <pagebreak_flag>True</pagebreak_flag>
    <row_height>1</row_height>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
    <repeat_flag>True</repeat_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
    <row_height>5</row_height>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_COUNT_01.stkentcode</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>150</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_STKAUDIT_COUNT_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_STKAUDIT_COUNT_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_STKAUDIT_COUNT_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_STKAUDIT_COUNT_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_STKAUDIT_COUNT_01.stkentcode</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>={LV_ITEM_01.section}&amp;'' - ''&amp;{LV_ITEM_01.department}</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>=If({LV_ITEM_01.barcode}='''', {LV_ITEM_01.code}, {LV_ITEM_01.barcode})</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STKAUDIT_COUNT_01.batch_serial_string</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_STKAUDIT_COUNT_01.stkentcode</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>989302378</filter_ref_id>
    <filter_title />
    <values>
      <value>@DocumentId@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2021-02-09 16:47:04', '1300', '2026-10-05 08:57:19.791319',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 3,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026011', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    'cef34b25-c480-4866-81f8-697310e9a4f6', '1157ccb6-852a-4e1c-98d7-310e410c97ab', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026011', 'U'
);
