-- =====================================================
-- INSERT statement for content_id: 2a155b57-dd81-434f-84c7-a4f67d9250cc
-- Name: #Inventory Movement (Summary)#
-- Action: UPDATE
-- Version: 2026011
-- Generated on: 2026-09-28 14:07:37
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '2a155b57-dd81-434f-84c7-a4f67d9250cc', 0, 0,
    NULL, '#Inventory Movement (Summary)#', 'This Report will display Inventory Movement in summarize form considering Opening, Inward, Outward and Closing.',
    '<report>
  <main>
    <id>2a155b57-dd81-434f-84c7-a4f67d9250cc</id>
    <report_name>#Inventory Movement (Summary)#</report_name>
    <folder_name>Inventory\Status\StockBook</folder_name>
    <folder_id>18c0494f-c120-4353-832f-993c94e8a3b7</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>Letter</page_size>
    <page_orientation>Landscape</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This Report will display Inventory Movement in summarize form considering Opening, Inward, Outward and Closing.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <show_html_toolbar>Always</show_html_toolbar>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>SQ_STOCK_BOOK_SUMMARY_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|03-Composite</category>
  </entity>
  <cell>
    <id>171783021</id>
    <cell_text>=@ConnOUName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1367633393</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1866114085</id>
    <cell_text>=Bold(''Period: '')&amp;@SBSMonthFrom@&amp;Bold('' To '')&amp;@SBSMonthTo@&amp;If(ExecuteQuery("select case when dtto &gt;= current_date then ''Yes'' else ''No''end monthchk from admmonth where month_name = right(''"&amp;@SBSMonthTo@&amp;"'',6)")=''Yes'',''(Till : ''&amp;GlobalDateFormat(Today())&amp;'')'','''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>193012941</id>
    <cell_text>=@IsCategory1@&amp;@IsCategory2@&amp;@IsCategory3@&amp;@IsCategory4@&amp;@IsCategory5@&amp;@IsCategory6@&amp;@IsBarcodeApplicable@&amp;@IsDescription1@&amp;@IsDescription2@&amp;@IsDescription3@&amp;@IsDescription4@&amp;@IsDescription5@&amp;@IsDescription6@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>534452981</id>
    <cell_text>Site Name [Short Name]</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>802508478</id>
    <cell_text>=If(@ReportLevelInvMove@=''A). Site'','''',''Division'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>107193196</id>
    <cell_text>=If(Or(@ReportLevelInvMove@=''A). Site'',@ReportLevelInvMove@=''B). Division''), '''', ''Section'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>156969025</id>
    <cell_text>=If(Or(@ReportLevelInvMove@=''A). Site'',@ReportLevelInvMove@=''B). Division'', @ReportLevelInvMove@=''C). Section''), '''', ''Department'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>26893085</id>
    <cell_text>=If(@ReportLevelInvMove@=''E). Item Description'', ''Item Description'', '''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1271024380</id>
    <cell_text>Quantity</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>469214159</id>
    <cell_text>Cost Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1828268741</id>
    <cell_text>Transit Closing</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1555592616</id>
    <cell_text>Opening</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1881544537</id>
    <cell_text>Inward</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1316326341</id>
    <cell_text>Outward</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1717867439</id>
    <cell_text>Closing</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>224667722</id>
    <cell_text>Opening</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2113413420</id>
    <cell_text>Inward</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>199136246</id>
    <cell_text>Outward</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1049609360</id>
    <cell_text>Closing</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>366941381</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2108635400</id>
    <cell_text>Cost Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1453567013</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>186470810</id>
    <cell_text>=[F17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>704949791</id>
    <cell_text>=[G17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1623036034</id>
    <cell_text>=[H17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1881471092</id>
    <cell_text>=[I17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>184994359</id>
    <cell_text>=[J17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>287421776</id>
    <cell_text>=[K17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>197951532</id>
    <cell_text>=[L17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2017552585</id>
    <cell_text>=[M17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1130486689</id>
    <cell_text>=[N17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>594014365</id>
    <cell_text>=[O17]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1177128355</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#606060</foreground_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1951017048</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>@ReportLevelInvMove@=''A). Site''</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>126003816</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1563116012</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>18406839</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>117847222</id>
    <cell_text>=[F16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2131981041</id>
    <cell_text>=[G16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1520803396</id>
    <cell_text>=[H16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1573228528</id>
    <cell_text>=[I16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1642648268</id>
    <cell_text>=[J16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>545698161</id>
    <cell_text>=[K16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>111501634</id>
    <cell_text>=[L16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>730281941</id>
    <cell_text>=[M16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1953602989</id>
    <cell_text>=[N16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>521513432</id>
    <cell_text>=[O16]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1255187193</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#606060</foreground_color>
  </cell>
  <cell>
    <id>1055900771</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1951537580</id>
    <cell_text>LV_ITEM_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <conditional>
      <formula>Or(@ReportLevelInvMove@=''A). Site'',@ReportLevelInvMove@=''B). Division'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>732377285</id>
    <cell_text>=[F15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>782646735</id>
    <cell_text>=[G15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>957465207</id>
    <cell_text>=[H15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>677266303</id>
    <cell_text>=[I13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1173336488</id>
    <cell_text>=[J15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>378723062</id>
    <cell_text>=[K15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>2071938639</id>
    <cell_text>=[L15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1215589194</id>
    <cell_text>=[M15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1647929047</id>
    <cell_text>=[N15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1927268628</id>
    <cell_text>=[O15]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1072863639</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#606060</foreground_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1533541044</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2106290993</id>
    <cell_text>LV_ITEM_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1714597579</id>
    <cell_text>LV_ITEM_01.department</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>Or(@ReportLevelInvMove@=''A). Site'',@ReportLevelInvMove@=''B). Division'',@ReportLevelInvMove@=''C). Section'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1660572574</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>940885363</id>
    <cell_text>=[F14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>825313424</id>
    <cell_text>=[G14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>144870402</id>
    <cell_text>=[H14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2144422539</id>
    <cell_text>=[I14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>767363509</id>
    <cell_text>=[J14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1633464612</id>
    <cell_text>=[K14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1761178947</id>
    <cell_text>=[L14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>787510593</id>
    <cell_text>=[M14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2055130777</id>
    <cell_text>=[N14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1730164557</id>
    <cell_text>=[O14]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>350161941</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#606060</foreground_color>
  </cell>
  <cell>
    <id>948246056</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>21281114</id>
    <cell_text>LV_ITEM_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
  </cell>
  <cell>
    <id>828471824</id>
    <cell_text>LV_ITEM_01.department</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#606060</foreground_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1634213281</id>
    <cell_text>LV_ITEM_01.item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>@ReportLevelInvMove@!=''E). Item Description''</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1934248135</id>
    <cell_text>=[F13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1028448522</id>
    <cell_text>=[G13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1186449936</id>
    <cell_text>=[H13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>752960685</id>
    <cell_text>=[I13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1242882623</id>
    <cell_text>=[J13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>494257142</id>
    <cell_text>=[K13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>882310599</id>
    <cell_text>=[L13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1130833876</id>
    <cell_text>=[M13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>263640879</id>
    <cell_text>=[N13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>267276340</id>
    <cell_text>=[O13]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>442042093</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.closing_stock_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1711985498</id>
    <cell_text>={SQ_STOCK_BOOK_SUMMARY_01.opening_quantity}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1091537655</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.inward_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>696757741</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.outward_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1686202339</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.closing_transit_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1272700707</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.opening_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1971069403</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.inward_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>998509169</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.outward_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1586453249</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.closing_stock_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1758811075</id>
    <cell_text>SQ_STOCK_BOOK_SUMMARY_01.closing_transit_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <sum_flag>True</sum_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1383822622</id>
    <cell_text>=aggsum([F13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1413573446</id>
    <cell_text>=aggsum([G13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2079525768</id>
    <cell_text>=aggsum([H13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>664509026</id>
    <cell_text>=aggsum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>4899512</id>
    <cell_text>=aggsum([J13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1068719775</id>
    <cell_text>=aggsum([K13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1672015904</id>
    <cell_text>=aggsum([L13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>468563222</id>
    <cell_text>=aggsum([M13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>837931136</id>
    <cell_text>=aggsum([N13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>824812303</id>
    <cell_text>=aggsum([O13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1264490183</id>
    <cell_text>=aggsum([F14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1448141577</id>
    <cell_text>=aggsum([G14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>765353824</id>
    <cell_text>=aggsum([H14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>392266713</id>
    <cell_text>=aggsum([I14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>422651719</id>
    <cell_text>=aggsum([J14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1125140971</id>
    <cell_text>=aggsum([K14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>221459840</id>
    <cell_text>=aggsum([L14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2000094044</id>
    <cell_text>=aggsum([M14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>43806625</id>
    <cell_text>=aggsum([N14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1043954272</id>
    <cell_text>=aggsum([O14])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1812024615</id>
    <cell_text>=aggsum([F15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1844901030</id>
    <cell_text>=aggsum([G15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>758660394</id>
    <cell_text>=aggsum([H15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2122658830</id>
    <cell_text>=aggsum([I15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>883721933</id>
    <cell_text>=aggsum([J15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>178818987</id>
    <cell_text>=aggsum([K15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>925643107</id>
    <cell_text>=aggsum([L15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>406523962</id>
    <cell_text>=aggsum([M15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1578481340</id>
    <cell_text>=aggsum([N15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>205480133</id>
    <cell_text>=aggsum([O15])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1354413396</id>
    <cell_text>=aggsum([F16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1549135606</id>
    <cell_text>=aggsum([G16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>290981179</id>
    <cell_text>=aggsum([H16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>515239335</id>
    <cell_text>=aggsum([I16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1136415128</id>
    <cell_text>=aggsum([J16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>303626679</id>
    <cell_text>=aggsum([K16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1550376444</id>
    <cell_text>=aggsum([L16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1265567724</id>
    <cell_text>=aggsum([M16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>866894109</id>
    <cell_text>=aggsum([N16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2022675433</id>
    <cell_text>=aggsum([O16])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1465469738</id>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1952165523</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>304674184</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>178329472</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>242647409</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1063554690</id>
    <cell_text>=aggsum([F17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1454180706</id>
    <cell_text>=aggsum([G17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>91032793</id>
    <cell_text>=aggsum([H17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2095447901</id>
    <cell_text>=aggsum([I17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1334979435</id>
    <cell_text>=aggsum([J17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>495499613</id>
    <cell_text>=aggsum([K17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1599656473</id>
    <cell_text>=aggsum([L17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>493331391</id>
    <cell_text>=aggsum([M17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>664690649</id>
    <cell_text>=aggsum([N17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1213497901</id>
    <cell_text>=aggsum([O17])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>900314115</id>
    <cell_text>=Concatenate(''When Report Level Selection is Site/Division/Section/Department then Show Barcode, Show Category1,Show Category 2, Show Category3, Show Category4,Show Category5, Show Category6 selection is ineffective.'',''&lt;br&gt;'',''This will be visible only when report level selection is Item Description.'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>267079360</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>14</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>958981572</id>
    <cell_text>NB :  (i) Misc. Issue is considered in Outward Transaction and Misc. Receive is considered in Inward Transaction. (ii) +ve Adjustments considered in Inward Transaction where as -ve Adjustments are considered in Outward Transaction. (iii) Outward Value shown with -ve sign hence, Closing value can be achived by following formula Opening + Inward + Outward = Closing</cell_text>
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
  </cell>
  <cell>
    <id>1678272007</id>
    <cell_text>=''Print Date: ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>552582079</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>836017685</id>
    <cell_text>=''Page No.: ''&amp;@pageNumber@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
    <row_height>2</row_height>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_SITE_01.name</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_ITEM_01.division</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_ITEM_01.section</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_ITEM_01.department</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_ITEM_01.item_name</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <suppress_flag>True</suppress_flag>
    <row_height>15</row_height>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.item_name</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.department</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.section</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.division</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_SITE_01.name</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>220</column_width>
  </column>
  <column>
    <column_width>135</column_width>
  </column>
  <column>
    <column_width>138</column_width>
  </column>
  <column>
    <column_width>139</column_width>
  </column>
  <column>
    <column_width>202</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>SQ_STOCK_BOOK_SUMMARY_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>SQ_STOCK_BOOK_SUMMARY_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>barcode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>barcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>SQ_STOCK_BOOK_SUMMARY_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>SQ_STOCK_BOOK_SUMMARY_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_SITE_01.name</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.division</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.section</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.department</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.item_name</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_SITE_01.site_type</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>333881266</filter_ref_id>
    <filter_title>Site Type</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_SITE_01.display_name_shortcode</filter_name>
    <order_num>1</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>426820094</filter_ref_id>
    <filter_title>Site Name | Short Code</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.barcode</filter_name>
    <order_num>2</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>738877520</filter_ref_id>
    <filter_title>Barcode</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>asc</direction>
  </topn>
  <serverevent>
    <event_type>OnExecuteSqlStatementConstructed</event_type>
    <event_id>0</event_id>
  </serverevent>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2024-05-31 07:51:21.953936', '16148', '2026-09-28 08:05:04.307686',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026011', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '2a155b57-dd81-434f-84c7-a4f67d9250cc', '22c5e015-ecdc-4bce-aa15-d1e4270a1a7d', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026011', 'U'
);
