-- =====================================================
-- INSERT statement for content_id: e5a6a882-a310-4fc6-825e-09d9a78e22d1
-- Name: #Miscelleneous Issue - Transfer#
-- Action: UPDATE
-- Version: 2026011
-- Generated on: 2026-10-05 14:31:43
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    'e5a6a882-a310-4fc6-825e-09d9a78e22d1', 0, 0,
    NULL, '#Miscelleneous Issue - Transfer#', 'This is a Miscellaneous Issue or Receipt Document Report used for adhoc Stock Transfer document printing purpose. Should be executed from Miscellaneous Issue or Receipt only.',
    '<report>
  <main>
    <id>e5a6a882-a310-4fc6-825e-09d9a78e22d1</id>
    <report_name>#Miscelleneous Issue - Transfer#</report_name>
    <folder_name>Inventory\Documents</folder_name>
    <folder_id>3942da7c-bf44-4c44-8eff-f42cf75a97b2</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>4,1,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This is a Miscellaneous Issue or Receipt Document Report used for adhoc Stock Transfer document printing purpose. Should be executed from Miscellaneous Issue or Receipt only.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>True</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>True</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>-1</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ARAP_SUB_LEDGER_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_MISC_ENTRY_HEADER_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|02-Transaction|*{*}*|Miscellaneous Entry</category>
  </entity>
  <entity>
    <entity_name>LV_MISC_ISSUE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|03-Composite</category>
  </entity>
  <entity>
    <entity_name>LV_MISC_ENTRY_HSN_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|02-Transaction|*{*}*|Miscellaneous Entry</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_02</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>738726035</id>
    <cell_text>@ExecutingSQL@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>26</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>911216230</id>
    <cell_text>=If(@PrintLogo@=''Y'', OULogo(), '''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>10164398</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>1</cell_row>
    <cell_col>23</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>265771811</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1896746769</id>
    <cell_text>=If(@ReportTitle@!='''', @ReportTitle@, ''Miscellaneous Transfer'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>26</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1472280423</id>
    <cell_text>LV_SITE_01.address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>586697671</id>
    <cell_text>={LV_SITE_01.phone1}&amp;'' ''&amp;{LV_SITE_01.phone2}&amp;'' ''&amp;{LV_SITE_01.phone3}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>805741887</id>
    <cell_text>={LV_SITE_01.email1}&amp;If({LV_SITE_01.email1}!='''', '', ''&amp;{LV_SITE_01.email2}, {LV_SITE_01.email2})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1810355412</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>25</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>607609555</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>32</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1019427111</id>
    <cell_text>={LV_SITE_01.website}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>197485729</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>16</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>114290921</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>25</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1527659681</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>32</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1661927977</id>
    <cell_text>CIN No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1504027461</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1050693414</id>
    <cell_text>LV_SITE_01.ou_cin</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>137981219</id>
    <cell_text>Transaction No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1918643922</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2098910949</id>
    <cell_text>LV_MISC_ISSUE_01.misc_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1882327374</id>
    <cell_text>GSTIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>742028569</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>46597585</id>
    <cell_text>={LV_SITE_01.gst_identification_no}&amp; ''[''&amp;{LV_SITE_01.gst_state_code}&amp;'' -''&amp;{LV_SITE_01.gst_state_name}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>2137435403</id>
    <cell_text>Transaction Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>900234429</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2053644552</id>
    <cell_text>LV_MISC_ISSUE_01.misc_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>698891248</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>38</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1118831113</id>
    <cell_text>Article / Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>If(LineNumberWithReset({LV_MISC_ISSUE_01.misc_code},''header'')=1, ''True'', ''False'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>25932471</id>
    <cell_text>Item Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1724844831</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>19</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1056677401</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>71693570</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>824681369</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1281240628</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1968357608</id>
    <cell_text>Bill To</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2095524204</id>
    <cell_text>Ship To</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>16</cell_col>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1405323972</id>
    <cell_text>LV_ARAP_SUB_LEDGER_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1421698125</id>
    <cell_text>={LV_MISC_ENTRY_HEADER_01.cost_center_site}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1943545449</id>
    <cell_text>LV_ARAP_SUB_LEDGER_01.billing_address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1869412611</id>
    <cell_text>LV_SITE_02.address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>614147340</id>
    <cell_text>={LV_ARAP_SUB_LEDGER_01.billing_city}&amp;If({LV_ARAP_SUB_LEDGER_01.billing_city}!='''', '' -''&amp;{LV_ARAP_SUB_LEDGER_01.billing_pincode}, {LV_ARAP_SUB_LEDGER_01.billing_pincode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>101429395</id>
    <cell_text>={LV_SITE_02.city}&amp;If({LV_SITE_02.city}!='''', '' - ''&amp;{LV_SITE_02.pincode}, {LV_SITE_02.pincode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1615580850</id>
    <cell_text>LV_ARAP_SUB_LEDGER_01.billing_office_phone1</cell_text>
    <cell_type>data</cell_type>
    <cell_row>16</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>511359040</id>
    <cell_text>={LV_SITE_02.phone1}&amp;If({LV_SITE_02.phone1}!='''', '' , ''&amp;{LV_SITE_02.phone1} , {LV_SITE_02.phone1})&amp;If(Or({LV_SITE_02.phone1}!='''',{LV_SITE_02.phone2}!=''''), '' ,''&amp;{LV_SITE_02.phone3}, {LV_SITE_02.phone3})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>25746401</id>
    <cell_text>={LV_ARAP_SUB_LEDGER_01.billing_email1}&amp;If({LV_ARAP_SUB_LEDGER_01.billing_email1}!='''', If({LV_ARAP_SUB_LEDGER_01.billing_email2}!='''', '' , ''&amp;{LV_ARAP_SUB_LEDGER_01.shipping_email2}, ''''), {LV_ARAP_SUB_LEDGER_01.billing_email2})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1620394932</id>
    <cell_text>={LV_SITE_02.email1}&amp;If({LV_SITE_02.email1}!='''', '' - ''&amp;{LV_SITE_02.email2}, {LV_SITE_02.email2})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1970862332</id>
    <cell_text>={LV_ARAP_SUB_LEDGER_01.gst_identification_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1655747022</id>
    <cell_text>={LV_SITE_02.gst_identification_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>145777052</id>
    <cell_text>={LV_ARAP_SUB_LEDGER_01.gst_state_name}&amp;If({LV_ARAP_SUB_LEDGER_01.gst_state_name}!='''', If({LV_ARAP_SUB_LEDGER_01.gst_state_code}!='''', ''-''&amp;{LV_ARAP_SUB_LEDGER_01.gst_state_code}, ''''), {LV_ARAP_SUB_LEDGER_01.gst_state_code})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1997922690</id>
    <cell_text>=If({LV_SITE_02.gst_state_name}!=Null(),{LV_SITE_02.gst_state_name}&amp;'' (''&amp;{LV_SITE_02.gst_state_code}&amp;'')'','''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>22</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>58652095</id>
    <cell_text>Doc No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>495784413</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>19</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>682893616</id>
    <cell_text>={LV_MISC_ENTRY_HEADER_01.general_doc_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>20</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1851238636</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2139507232</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>906434493</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1475894976</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>76171187</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1447832725</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1421650169</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>758565099</id>
    <cell_text>Remarks</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1215468100</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>19</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1145060223</id>
    <cell_text>={LV_MISC_ENTRY_HEADER_01.remarks}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>20</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1139344381</id>
    <cell_text>@ReportHeader@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>22</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>38</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>687520542</id>
    <cell_text>Barcode</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>170974566</id>
    <cell_text>Item Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1128947512</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>19</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1161908466</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1711178610</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1352475825</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1826967690</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1541643363</id>
    <cell_text>=If({LV_ITEM_01.barcode}='''', {LV_MISC_ISSUE_01.icode}, {LV_ITEM_01.barcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <conditional>
      <formula>If({LV_MISC_ISSUE_01.quantity}=Null(), ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>29341598</id>
    <cell_text>={LV_ITEM_01.category1}&amp;'' ''&amp;{LV_ITEM_01.category2}&amp;'' ''&amp;{LV_ITEM_01.category3}&amp;'' ''&amp;{LV_ITEM_01.category4}&amp;'' ''&amp;{LV_ITEM_01.category5}&amp;'' ''&amp;{LV_ITEM_01.category6}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>If(CellValue()='' '', ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>465401519</id>
    <cell_text>LV_ITEM_01.hsn_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>24</cell_row>
    <cell_col>19</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>776113016</id>
    <cell_text>LV_MISC_ISSUE_01.rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>24</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1976472473</id>
    <cell_text>LV_MISC_ISSUE_01.quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>24</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1691970898</id>
    <cell_text>LV_ITEM_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>24</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>113492607</id>
    <cell_text>={LV_MISC_ISSUE_01.rate}*{LV_MISC_ISSUE_01.quantity}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>838786457</id>
    <cell_text>=If({LV_ITEM_01.item_management_mode}=''B'', ''Batch : ''&amp;{LV_MISC_ISSUE_01.batch_serial_string}, ''Serial : ''&amp;{LV_MISC_ISSUE_01.batch_serial_string})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>25</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>34</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <foreground_color>#BFBFBF</foreground_color>
    <conditional>
      <formula>Or([E26]=''Batch : '',[E26]=''Serial : '')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1153488230</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>24870371</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>719986695</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2062185935</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>889211532</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1370915527</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>526115720</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>986974365</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>13</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>98679377</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>32884045</id>
    <cell_text>Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>19</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>356909899</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>25</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>893973222</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>26</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>494219061</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>28</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1728279034</id>
    <cell_text>=AggSum({LV_MISC_ISSUE_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>26</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1906427769</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>32</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>673857274</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>33</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1706839621</id>
    <cell_text>=AggSum([AI25])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>26</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1678626761</id>
    <cell_text>Amount In Words</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>570471348</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>821175545</id>
    <cell_text>=AmountinWords([AI27])&amp;'' Only''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>7</cell_col>
    <cell_colspan>31</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1076817612</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>940354309</id>
    <cell_text>Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1751018207</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>26</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1836149884</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1758976850</id>
    <cell_text>LV_MISC_ENTRY_HSN_01.hsn_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>29</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1939493445</id>
    <cell_text>LV_MISC_ENTRY_HSN_01.amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>29</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1639766758</id>
    <cell_text>LV_MISC_ENTRY_HSN_01.item_qty</cell_text>
    <cell_type>data</cell_type>
    <cell_row>29</cell_row>
    <cell_col>26</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1879945212</id>
    <cell_text>LV_MISC_ENTRY_HSN_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>29</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>283341059</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>363188562</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>378549434</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>681370780</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1276876815</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1322309257</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1716852916</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>156278254</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1696642003</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>383092051</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1676436366</id>
    <cell_text>Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>629529283</id>
    <cell_text>=AggSum({LV_MISC_ENTRY_HSN_01.amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>30</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1418389418</id>
    <cell_text>=AggSum({LV_MISC_ENTRY_HSN_01.item_qty})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>30</cell_row>
    <cell_col>26</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1432452887</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>32</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>92255868</id>
    <cell_text>=@ReportFooter@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>38</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>214161433</id>
    <cell_text>=''For ''&amp;@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>33</cell_row>
    <cell_col>25</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1460955675</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>36</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1538265208</id>
    <cell_text>Prepared By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>462111472</id>
    <cell_text>Checked By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1726555286</id>
    <cell_text>Passed By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>28</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1395047556</id>
    <cell_text>LV_MISC_ENTRY_HEADER_01.created_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>38</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1772927789</id>
    <cell_text>=''[''&amp;GlobalDateFormat({LV_MISC_ENTRY_HEADER_01.creation_time})&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>39</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1765375098</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>40</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>606568873</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>10</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>215572225</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>14</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>372938748</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1983101143</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1272234075</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>61840367</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>238265919</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>19</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1807359673</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>20</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1476701504</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>21</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2042019014</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>22</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>468105870</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>23</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1099301985</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2108775610</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1541930240</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2132689297</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>27</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>519959346</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>28</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1671015669</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>29</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>927639074</id>
    <cell_text>=''Page :  ''&amp;PageNoWithReset({LV_MISC_ENTRY_HEADER_01.misccode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>40</cell_row>
    <cell_col>30</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <row_height>4</row_height>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <pagebreak_flag>True</pagebreak_flag>
    <row_height>1</row_height>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
    <row_height>25</row_height>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
    <row_height>5</row_height>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_MISC_ENTRY_HEADER_01.misccode</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>150</column_width>
  </column>
  <column>
    <column_width>150</column_width>
  </column>
  <column>
    <column_width>130</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>70</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>130</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_MISC_ISSUE_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_MISC_ISSUE_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_MISC_ENTRY_HEADER_01</entity_from_name>
    <entity_to_name>LV_MISC_ENTRY_HSN_01</entity_to_name>
    <entity_from_id>LV_MISC_ENTRY_HEADER_01</entity_from_id>
    <entity_to_id>LV_MISC_ENTRY_HSN_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>misccode</col_from_name>
      <col_to_name>misccode</col_to_name>
    </key>
    <clause>
      <left_side>misccode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>misccode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_MISC_ENTRY_HEADER_01</entity_from_name>
    <entity_to_name>LV_MISC_ISSUE_01</entity_to_name>
    <entity_from_id>LV_MISC_ENTRY_HEADER_01</entity_from_id>
    <entity_to_id>LV_MISC_ISSUE_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>misccode</col_from_name>
      <col_to_name>misc_code</col_to_name>
    </key>
    <clause>
      <left_side>misccode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>misc_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_02</entity_from_name>
    <entity_to_name>LV_MISC_ENTRY_HEADER_01</entity_to_name>
    <entity_from_id>LV_SITE_02</entity_from_id>
    <entity_to_id>LV_MISC_ENTRY_HEADER_01</entity_to_id>
    <join_type>rightouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_cc</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_cc</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_MISC_ENTRY_HEADER_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_MISC_ENTRY_HEADER_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ARAP_SUB_LEDGER_01</entity_from_name>
    <entity_to_name>LV_SITE_02</entity_to_name>
    <entity_from_id>LV_ARAP_SUB_LEDGER_01</entity_from_id>
    <entity_to_id>LV_SITE_02</entity_to_id>
    <join_type>rightouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>slcode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>slcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_MISC_ENTRY_HEADER_01.misccode</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>={LV_ITEM_01.section}&amp;'' - ''&amp;{LV_ITEM_01.department}</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>=If({LV_ITEM_01.barcode}='''', {LV_MISC_ISSUE_01.icode}, {LV_ITEM_01.barcode})</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_MISC_ISSUE_01.batch_serial_string</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_MISC_ENTRY_HSN_01.hsn_code</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_MISC_ENTRY_HEADER_01.misccode</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1285142061</filter_ref_id>
    <filter_title />
    <values>
      <value>@DocumentId@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2021-02-09 16:47:03', '1300', '2026-10-05 08:55:11.978940',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 3,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026011', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    'e5a6a882-a310-4fc6-825e-09d9a78e22d1', '1157ccb6-852a-4e1c-98d7-310e410c97ab', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026011', 'U'
);
