-- =====================================================
-- INSERT statement for content_id: e46c08a8-bf3a-4e21-a39a-1a1a1cef6b07
-- Name: #Transfer In#
-- Action: UPDATE
-- Version: 2026010
-- Generated on: 2026-09-11 14:39:17
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    'e46c08a8-bf3a-4e21-a39a-1a1a1cef6b07', 0, 0,
    NULL, '#Transfer In#', 'This is a Transfer In Invoice Document Report, to be used for document printing purpose. Should be executed from Transfer In Transactions only',
    '<report>
  <main>
    <id>e46c08a8-bf3a-4e21-a39a-1a1a1cef6b07</id>
    <report_name>#Transfer In#</report_name>
    <folder_name>Sales And Distribution\Documents</folder_name>
    <folder_id>da40565f-42fe-4e5f-9383-197beb5f2beb</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>4,1,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This is a Transfer In Invoice Document Report, to be used for document printing purpose. Should be executed from Transfer In Transactions only</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>True</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>RQ_SALRT_TRIN_DOC_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>Report Specific|*{*}*|Document|*{*}*|Sales Return - Transfer In</category>
  </entity>
  <cell>
    <id>381007924</id>
    <cell_text>=@ExecutingSQL@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>75602278</id>
    <cell_text>Original - Buyer''s Copy / Seller''s Copy / Transporter''s Copy</cell_text>
    <cell_type>text</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>12</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1670453157</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_refsite_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2076239129</id>
    <cell_text>=If(@ReportTitle@='''', ''Consignment/Transfer Return'', @ReportTitle@)</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1003927937</id>
    <cell_text>Site :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>598440482</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l1_refsite_name}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>780202550</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l1_refsite_address}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>648836376</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>9</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>583645541</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>332080331</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l1_refsite_phone1}=DbNull(), '''', ''Phone : ''&amp;{RQ_SALRT_TRIN_DOC_01.l1_refsite_phone1})&amp;If({fax}=DbNull(), '''', ''Fax: ''&amp;{fax}&amp;'','')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>986257580</id>
    <cell_text>GSTIN :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1711457767</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l1_refsite_gstin_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>949740380</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2120965140</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l1_owner_site_website}=DbNull(), '''', ''Website:- ''&amp;{RQ_SALRT_TRIN_DOC_01.l1_owner_site_website})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1557062397</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2058911952</id>
    <cell_text>GST STATE:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1651685752</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l1_refsite_gstin_no}='''', '''', {RQ_SALRT_TRIN_DOC_01.l1_refsite_gst_state_name}&amp;''[''&amp;{RQ_SALRT_TRIN_DOC_01.l1_refsite_gst_state_code}&amp;'']'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>928453019</id>
    <cell_text>Customer</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2047282191</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>839757320</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_cust_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1918555704</id>
    <cell_text>Invoice No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>733953712</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1669955058</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_return_invoice_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1362396260</id>
    <cell_text>Site</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1349832683</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>363382570</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_refsite_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>662976786</id>
    <cell_text>Invoice Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1702421261</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>603670386</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_return_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1269472553</id>
    <cell_text>Address</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1430514525</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1869445939</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_refsite_address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>400239460</id>
    <cell_text>Logistics No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>306382281</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>936042521</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_logistic_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1314979936</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_refsite_city</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1440590839</id>
    <cell_text>Logistics Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>66024294</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1278643123</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_logistic_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>211417334</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_refsite_pincode</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1346089284</id>
    <cell_text>Declared Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>11</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>95050341</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>11</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>559058621</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_logistic_declared_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1366975281</id>
    <cell_text>GST IN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1983853901</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1678786682</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_cust_gstin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>2127402894</id>
    <cell_text>Document No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1392623907</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1130693133</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_document_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1490238506</id>
    <cell_text>GST State</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1722069217</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>309845129</id>
    <cell_text>=if({RQ_SALRT_TRIN_DOC_01.l1_cust_gstin_no}=DbNull(),'''',{RQ_SALRT_TRIN_DOC_01.l1_cust_gst_state_code}&amp;''(''&amp;{RQ_SALRT_TRIN_DOC_01.l1_cust_gst_state_name}&amp;'')'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1363903473</id>
    <cell_text>Document Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>2064125206</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>829573342</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_document_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>762895190</id>
    <cell_text>Agent</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>452630102</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>12903869</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_agent_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>If(CellValue()=''No Agent'', True(), False())</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1859368846</id>
    <cell_text>In Stock Point</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>594364989</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>715631972</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_stock_point_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>15</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1310042263</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1911093271</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>541014826</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1983811480</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1782589014</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1087570521</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1179234320</id>
    <cell_text>=@ReportHeader@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>371678453</id>
    <cell_text>Sl No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>360250659</id>
    <cell_text>Particulars</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>518486859</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>219646731</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1919875248</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>952518720</id>
    <cell_text>Quantity</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1880854609</id>
    <cell_text>Unit</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1471966637</id>
    <cell_text>Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>319125558</id>
    <cell_text>=LineNumberWithReset({RQ_SALRT_TRIN_DOC_01.rtcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1061139814</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l2_detail_division}&amp;''-''&amp;{RQ_SALRT_TRIN_DOC_01.l2_detail_section}&amp;''-''&amp;{RQ_SALRT_TRIN_DOC_01.l2_detail_department}&amp;''-''&amp;If({RQ_SALRT_TRIN_DOC_01.l2_detail_barcode}='''', {item_code}, {RQ_SALRT_TRIN_DOC_01.l2_detail_barcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>If(CellValue()=''---'', True(), False())</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>820525309</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l2_detail_hsn_sac_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>18</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>77116498</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l2_detail_returned_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>18</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1129732697</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l2_detail_return_rsp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>18</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1266094372</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l2_detail_returned_quantity}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l2_detail_returned_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>465207769</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l2_detail_item_uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>18</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1518480548</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l2_detail_returned_rate}*{RQ_SALRT_TRIN_DOC_01.l2_detail_returned_quantity}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1906475330</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>[B19]=''''</formula>
      <action>SuppressRow</action>
    </conditional>
    <conditional>
      <formula>Or([B20]=''Batch : '',[B20]=''Serial : '')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>2038327760</id>
    <cell_text>=If({item_management_mode}=''B'', ''Batch : ''&amp;{LV_TRIN_ITEMDETAIL_01.batch_serial_string}, ''Serial : ''&amp;{LV_TRIN_ITEMDETAIL_01.batch_serial_string})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <foreground_color>#9F9F9F</foreground_color>
    <conditional>
      <formula>{item_management_mode}=''I''</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>16702369</id>
    <cell_text>Send :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>485440630</id>
    <cell_text>Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>296739784</id>
    <cell_text>=AggSum({LV_TRIN_ITEMDETAIL_01.send_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>882626519</id>
    <cell_text>Short/Excess :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1119312578</id>
    <cell_text>Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>44121380</id>
    <cell_text>=If(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_quantity})&gt;0,Abs(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_quantity})),Abs(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_quantity})))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>687051537</id>
    <cell_text>Receive :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>453533575</id>
    <cell_text>Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1384090086</id>
    <cell_text>=aggsum([K19])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1942137050</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2087558767</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>103415842</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1494485172</id>
    <cell_text>=AggSum({LV_TRIN_ITEMDETAIL_01.item_effective_value})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1759484456</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1864557928</id>
    <cell_text>=If(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_amount})&gt;0,Abs(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_amount})),Abs(AggSum({LV_TRIN_ITEMDETAIL_01.short_excess_amount})))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1144638230</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>536479849</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>678231422</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1590219939</id>
    <cell_text>=aggsum([N19])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1679736389</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l3_charge_charge_name}&amp;'' ''&amp;if({RQ_SALRT_TRIN_DOC_01.l3_charge_charge_basis}=''Percentage'',''[ @''&amp;'' ''&amp;VALUE({RQ_SALRT_TRIN_DOC_01.l3_charge_charge_rate})&amp;''% on ''&amp;VALUE({RQ_SALRT_TRIN_DOC_01.l3_charge_charge_applicable_on})&amp;'' ]'',''[ @''&amp;'' ''&amp;VALUE({RQ_SALRT_TRIN_DOC_01.l3_charge_charge_rate})&amp;'' on ''&amp;VALUE({RQ_SALRT_TRIN_DOC_01.l3_charge_charge_applicable_on})&amp;'' ]'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>22</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>533731382</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l3_charge_charge_amount}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>22</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>{RQ_SALRT_TRIN_DOC_01.seq}!=2</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1849793309</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>608623127</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1881325683</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1697309025</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>439443486</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>674387374</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>608208940</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1705707986</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1607471675</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1784722591</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>621698081</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1914984825</id>
    <cell_text>GRAND TOTAL :-</cell_text>
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>636268378</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l1_net_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>23</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1657206728</id>
    <cell_text>Amount :-</cell_text>
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>704531756</id>
    <cell_text>=AmountinWords({RQ_SALRT_TRIN_DOC_01.l1_net_amount},''Rs. '')&amp;'' Only''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1907474569</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>0</cell_col>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1644309382</id>
    <cell_text>Taxable Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>691605067</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1889676819</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>785106713</id>
    <cell_text>IGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>277876985</id>
    <cell_text>CGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1962436768</id>
    <cell_text>SGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1495183025</id>
    <cell_text>Cess GST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1988577155</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1353509006</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>417321891</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>51540646</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2095622790</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>494381973</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1419606774</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>14178368</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>878212430</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l4_hsn_hsn_code}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1401222128</id>
    <cell_text>={RQ_SALRT_TRIN_DOC_01.l4_hsn_taxable_amount}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>372886359</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l4_hsn_return_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>961049366</id>
    <cell_text>RQ_SALRT_TRIN_DOC_01.l4_hsn_uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>2089836219</id>
    <cell_text>=if({RQ_SALRT_TRIN_DOC_01.l4_hsn_igst_rate}=DbNull(),0,{RQ_SALRT_TRIN_DOC_01.l4_hsn_igst_rate})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>896211572</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_igst_amount}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_igst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>387811562</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_cgst_rate}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_cgst_rate})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>588652234</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_cgst_amount}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_cgst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>277410894</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_sgst_rate}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_sgst_rate})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1796224907</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_sgst_amount}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_sgst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1618671624</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_cess_rate}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_cess_rate})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>808413671</id>
    <cell_text>=If({RQ_SALRT_TRIN_DOC_01.l4_hsn_cess_amount}=DbNull(), 0, {RQ_SALRT_TRIN_DOC_01.l4_hsn_cess_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>27</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1835171846</id>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>814340917</id>
    <cell_text>=aggsum({RQ_SALRT_TRIN_DOC_01.l4_hsn_taxable_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <foreground_color>#000000</foreground_color>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>CellValue()=0</formula>
      <action>ForegroundColor</action>
      <attribute>#E2E2E2</attribute>
    </conditional>
  </cell>
  <cell>
    <id>1425041151</id>
    <cell_text>=AggSum({RQ_SALRT_TRIN_DOC_01.l4_hsn_return_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1632890021</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>28</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>205471077</id>
    <cell_text>=AggSum({RQ_SALRT_TRIN_DOC_01.l4_hsn_igst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1473163167</id>
    <cell_text>=AggSum({RQ_SALRT_TRIN_DOC_01.l4_hsn_cgst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1654554157</id>
    <cell_text>=AggSum({RQ_SALRT_TRIN_DOC_01.l4_hsn_sgst_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2063360233</id>
    <cell_text>=AggSum({RQ_SALRT_TRIN_DOC_01.l4_hsn_cess_amount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>28</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1969339765</id>
    <cell_text>=@ReportFooter@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>29</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>242725520</id>
    <cell_text>=''For ''&amp;@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>30</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <font_italic_flag>True</font_italic_flag>
  </cell>
  <cell>
    <id>37755603</id>
    <cell_text>=''Prepared By: ''&amp;{RQ_SALRT_TRIN_DOC_01.l1_created_by}&amp;''[''&amp;GlobalDateFormat({RQ_SALRT_TRIN_DOC_01.l1_created_on})&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>34</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2139439981</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>34</cell_row>
    <cell_col>10</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2063092060</id>
    <cell_text>AUTHORISED SIGNATORY</cell_text>
    <cell_type>text</cell_type>
    <cell_row>36</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2015030123</id>
    <cell_text>=''Print Date:- ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>37</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>119446540</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>878986138</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1484842122</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>365717654</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>429763621</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>168676773</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>37</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>854391862</id>
    <cell_text>=''Page No.:- ''&amp;@pageNumber@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>37</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <pagebreak_flag>True</pagebreak_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
    <repeat_flag>True</repeat_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_SALRT_TRIN_DOC_01.rtcode</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>75</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>80</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>150</column_width>
  </column>
  <sort>
    <sort_name>RQ_SALRT_TRIN_DOC_01.rtcode</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>={RQ_SALRT_TRIN_DOC_01.l2_detail_division}&amp;''-''&amp;{RQ_SALRT_TRIN_DOC_01.l2_detail_section}&amp;''-''&amp;{RQ_SALRT_TRIN_DOC_01.l2_detail_department}</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_SALRT_TRIN_DOC_01.l3_charge_operation_level</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>False</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_SALRT_TRIN_DOC_01.l3_charge_display_sequence</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>RQ_SALRT_TRIN_DOC_01.rtcode</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1854133884</filter_ref_id>
    <filter_title />
    <values>
      <value>@DocumentId@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2020-01-14 22:16:33', '1300', '2026-09-10 10:34:21.133720',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 3,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026010', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    'e46c08a8-bf3a-4e21-a39a-1a1a1cef6b07', '20b9972c-7bfe-4d71-ae13-d94c893e0645', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026010', 'U'
);
