-- =====================================================
-- INSERT statement for content_id: 699fea65-aa4d-43f3-8e60-bab269a5206a
-- Name: #Composite GST Report#
-- Action: UPDATE
-- Version: 2026010
-- Generated on: 2026-09-30 17:03:15
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '699fea65-aa4d-43f3-8e60-bab269a5206a', 0, 0,
    NULL, '#Composite GST Report#', 'This Report will display consoldated all transactions done in ginesys for the specified date range in which GST has been charged. This report can be used as help for GSTR filling.',
    '<report>
  <main>
    <id>699fea65-aa4d-43f3-8e60-bab269a5206a</id>
    <report_name>#Composite GST Report#</report_name>
    <folder_name>Finance\Register</folder_name>
    <folder_id>a6f05f3b-1ddd-4599-9716-37a686c3a3eb</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>2,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This Report will display consoldated all transactions done in ginesys for the specified date range in which GST has been charged. This report can be used as help for GSTR filling.
</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>COMPOSITEGST_ENTRY_SOURCE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>08-Cross Module|*{*}*|03-Composite</category>
  </entity>
  <entity>
    <entity_name>SQ_COMPOSITE_GST_TRNX_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>08-Cross Module|*{*}*|03-Composite</category>
  </entity>
  <cell>
    <id>1246053590</id>
    <cell_text>Composite GST Report</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>49</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1800307284</id>
    <cell_text>=Bold(''Period: '')&amp;GlobalDateFormat(@DTFR@)&amp;Bold('' To '')&amp;GlobalDateFormat(@DTTO@)</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>49</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1227293194</id>
    <cell_text>=Bold(''CP GSTIN Source : '')&amp;@CPGSTINSource@&amp;Bold('' | HSN SAC Source : '')&amp;@HSNSACSource@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>49</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>386616402</id>
    <cell_text>ENTRY_SOURCE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1025257280</id>
    <cell_text>ENTRY_SITE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1393365254</id>
    <cell_text>ENTRY_DATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1673788385</id>
    <cell_text>ENTRY_NO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>176721633</id>
    <cell_text>ENTRY_TRADETYPE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1403939091</id>
    <cell_text>ENTRY_NETVALUE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>252757981</id>
    <cell_text>DOCUMENT_STATUS</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>742594782</id>
    <cell_text>REF_DOC_NO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1349239463</id>
    <cell_text>REF_DOC_DATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1212706368</id>
    <cell_text>GST_APPLICABILITY</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1038407149</id>
    <cell_text>OWNER_GSTIN_STATE_CODE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>380144561</id>
    <cell_text>OWNER_GSTIN_REGISTRATION_DATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>469879090</id>
    <cell_text>ETIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2106780077</id>
    <cell_text>CP_GSTIN_NO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1832754732</id>
    <cell_text>CP_GSTIN_STATE_CODE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>14</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2034734809</id>
    <cell_text>CP_GST_REGISTRATION_STATUS</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>590872306</id>
    <cell_text>CP_NAME</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>890589088</id>
    <cell_text>CP_PAN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>55570715</id>
    <cell_text>CP_CONTACT_PERSON</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>212036515</id>
    <cell_text>CP_MOBILE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>19</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>658876009</id>
    <cell_text>CP_EMAIL</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>20</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1522505482</id>
    <cell_text>CP_CLASS</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>21</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1613744145</id>
    <cell_text>CP_AGENT_NAME</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>22</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1963227832</id>
    <cell_text>CP_AGENT_CLASS</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>23</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>493719576</id>
    <cell_text>ORIGINAL_INV_ENT_NO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1824041590</id>
    <cell_text>ORIGINAL_INV_ENT_DT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>923132853</id>
    <cell_text>ORIGINAL_INV_ENT_NETVALUE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>934446496</id>
    <cell_text>ORIGINAL_INV_REFNO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>27</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1950282723</id>
    <cell_text>ORIGINAL_INV_REFDT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>28</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>384536873</id>
    <cell_text>DNCN_REASON</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>29</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>902425848</id>
    <cell_text>HSN_SAC_CODE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>30</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1741846176</id>
    <cell_text>HSN_SAC_DESC</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>31</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>558861365</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2081226339</id>
    <cell_text>CGST_RATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>33</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1150548132</id>
    <cell_text>SGST_RATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1185856208</id>
    <cell_text>IGST_RATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>35</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1462462051</id>
    <cell_text>CESS_RATE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>36</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>603065</id>
    <cell_text>QUANTITY</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>37</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1086629590</id>
    <cell_text>TAXABLE_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>51888964</id>
    <cell_text>CGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>39</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1357514715</id>
    <cell_text>SGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>40</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1263235075</id>
    <cell_text>IGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>41</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>380713089</id>
    <cell_text>CESS_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>42</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>667369377</id>
    <cell_text>NET_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>43</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2030072986</id>
    <cell_text>INPUT_ELIGIBILITY</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>44</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>43196514</id>
    <cell_text>INPUT_CGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>45</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>357715826</id>
    <cell_text>INPUT_SGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>46</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1971479847</id>
    <cell_text>INPUT_IGST_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>47</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1118432096</id>
    <cell_text>INPUT_CESS_AMOUNT</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>48</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>182943637</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_source</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>854415963</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_site</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>861722278</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1427117261</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>446112527</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_tradetype</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>524614998</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.entry_netvalue</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2041137220</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.document_status</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1241426923</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.ref_doc_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1674498566</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.ref_doc_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>659479074</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.gst_applicability</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>461651425</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.owner_gstin_state_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1665633109</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.owner_gstin_registration_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1173258900</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.etin</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1756954651</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_gstin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>13</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>57271032</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_gstin_state_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>14</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1590502230</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_gst_registration_status</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>817035835</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1993479237</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_pan</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>17</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>742252699</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_contact_person</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>18</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>726422048</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_mobile</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>19</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>0</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>712794625</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_email</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>20</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1804914955</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_class</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>21</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1509665176</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_agent_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>22</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>514517768</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cp_agent_class</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>348300227</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.original_inv_ent_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>24</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>977081253</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.original_inv_ent_dt</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>25</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1870521929</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.original_inv_ent_netvalue</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>26</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2072448624</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.original_inv_refno</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>27</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1507107818</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.original_inv_refdt</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>28</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>220106354</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.dncn_reason</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>29</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2064317381</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.hsn_sac_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>119450601</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.hsn_sac_desc</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>31</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1960920508</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1583205793</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cgst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>33</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>896599192</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.sgst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>606986764</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.igst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>35</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>486284320</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cess_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>36</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>325612524</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>37</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>722713253</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.taxable_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1107697561</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>39</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1592262309</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.sgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>40</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1484454505</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.igst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>41</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1057653556</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.cess_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>42</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>867834024</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.net_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>43</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>965624111</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.input_eligibility</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>44</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>695946544</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.input_cgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>45</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2139413808</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.input_sgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>46</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>742042275</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.input_igst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>47</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1403054881</id>
    <cell_text>SQ_COMPOSITE_GST_TRNX_01.input_cess_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>48</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <column>
    <column_width>220</column_width>
    <column_label>ENTRY_SOURCE</column_label>
  </column>
  <column>
    <column_width>163</column_width>
    <column_label>ENTRY_SITE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>ENTRY_DATE</column_label>
  </column>
  <column>
    <column_width>139</column_width>
    <column_label>ENTRY_NO</column_label>
  </column>
  <column>
    <column_width>122</column_width>
    <column_label>ENTRY_TRADETYPE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>ENTRY_NETVALUE</column_label>
  </column>
  <column>
    <column_width>130</column_width>
    <column_label>DOCUMENT_STATUS</column_label>
  </column>
  <column>
    <column_width>130</column_width>
    <column_label>REF_DOC_NO</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>REF_DOC_DATE</column_label>
  </column>
  <column>
    <column_width>127</column_width>
    <column_label>GST_APPLICABILITY</column_label>
  </column>
  <column>
    <column_width>164</column_width>
    <column_label>OWNER_GSTIN_STATE_CODE</column_label>
  </column>
  <column>
    <column_width>192</column_width>
    <column_label>OWNER_GSTIN_REGISTRATION_DATE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>ETIN</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_GSTIN_NO</column_label>
  </column>
  <column>
    <column_width>138</column_width>
    <column_label>CP_GSTIN_STATE_CODE</column_label>
  </column>
  <column>
    <column_width>186</column_width>
    <column_label>CP_GST_REGISTRATION_STATUS</column_label>
  </column>
  <column>
    <column_width>165</column_width>
    <column_label>CP_NAME</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_PAN</column_label>
  </column>
  <column>
    <column_width>133</column_width>
    <column_label>CP_CONTACT_PERSON</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_MOBILE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_EMAIL</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_CLASS</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_AGENT_NAME</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CP_AGENT_CLASS</column_label>
  </column>
  <column>
    <column_width>148</column_width>
    <column_label>ORIGINAL_INV_ENT_NO</column_label>
  </column>
  <column>
    <column_width>137</column_width>
    <column_label>ORIGINAL_INV_ENT_DT</column_label>
  </column>
  <column>
    <column_width>179</column_width>
    <column_label>ORIGINAL_INV_ENT_NETVALUE</column_label>
  </column>
  <column>
    <column_width>170</column_width>
    <column_label>ORIGINAL_INV_REFNO</column_label>
  </column>
  <column>
    <column_width>148</column_width>
    <column_label>ORIGINAL_INV_REFDT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>DNCN_REASON</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>HSN_SAC_CODE</column_label>
  </column>
  <column>
    <column_width>148</column_width>
    <column_label>HSN_SAC_DESC</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>UOM</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CGST_RATE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>SGST_RATE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>IGST_RATE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CESS_RATE</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>QUANTITY</column_label>
  </column>
  <column>
    <column_width>121</column_width>
    <column_label>TAXABLE_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>SGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>IGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>CESS_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>NET_AMOUNT</column_label>
  </column>
  <column>
    <column_width>100</column_width>
    <column_label>INPUT_ELIGIBILITY</column_label>
  </column>
  <column>
    <column_width>148</column_width>
    <column_label>INPUT_CGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>137</column_width>
    <column_label>INPUT_SGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>168</column_width>
    <column_label>INPUT_IGST_AMOUNT</column_label>
  </column>
  <column>
    <column_width>150</column_width>
    <column_label>INPUT_CESS_AMOUNT</column_label>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>SQ_COMPOSITE_GST_TRNX_01</entity_from_name>
    <entity_to_name>COMPOSITEGST_ENTRY_SOURCE_01</entity_to_name>
    <entity_from_id>SQ_COMPOSITE_GST_TRNX_01</entity_from_id>
    <entity_to_id>COMPOSITEGST_ENTRY_SOURCE_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>entry_source</col_from_name>
      <col_to_name>entry_source</col_to_name>
    </key>
    <clause>
      <left_side>entry_source</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>entry_source</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <filter>
    <filter_name>SQ_COMPOSITE_GST_TRNX_01.owner_gstin_no</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1106494027</filter_ref_id>
    <filter_title>Owner GSTIN No.</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>SQ_COMPOSITE_GST_TRNX_01.document_status</filter_name>
    <order_num>1</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1164824361</filter_ref_id>
    <filter_title>Document Status</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>COMPOSITEGST_ENTRY_SOURCE_01.entry_source</filter_name>
    <order_num>2</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1140873615</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2024-05-30 06:13:12.079384', '16148', '2026-09-30 11:26:41.942736',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 25,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026010', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '699fea65-aa4d-43f3-8e60-bab269a5206a', 'f2821c20-e8af-47e4-8838-c491dae8633e', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026010', 'U'
);
