-- =====================================================
-- INSERT statement for content_id: 2f255744-ca2d-4922-9e96-569b391fdb21
-- Name: #Approval Pending Register#
-- Action: INSERT
-- Version: 2026010
-- Generated on: 2026-09-24 13:36:25
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '2f255744-ca2d-4922-9e96-569b391fdb21', 0, 0,
    NULL, '#Approval Pending Register#', 'This report will display the Entries which is Pending for Approval.',
    '<report>
  <main>
    <id>2f255744-ca2d-4922-9e96-569b391fdb21</id>
    <report_name>#Approval Pending Register#</report_name>
    <folder_name>Admin\Approval Workflow</folder_name>
    <folder_id>e17500c1-bfbc-495a-af33-62edc414e1ec</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>2,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will display the Entries which is Pending for Approval.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_APPRV_DOC_INST_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>08-Cross Module|*{*}*|04-Approval Workflow|*{*}*|Approval Doc</category>
  </entity>
  <entity>
    <entity_name>LV_APPRV_DOC_LEVEL_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>08-Cross Module|*{*}*|04-Approval Workflow|*{*}*|Approval Doc</category>
  </entity>
  <entity>
    <entity_name>LV_APPRV_DOC_TASK_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>08-Cross Module|*{*}*|04-Approval Workflow|*{*}*|Approval Doc</category>
  </entity>
  <cell>
    <id>1313838499</id>
    <cell_text>=@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>17</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>415852536</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>17</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>698152788</id>
    <cell_text>=Bold(''Period : '')&amp;GlobalDateFormat(@DTFR@)&amp;Bold(''  To : '')&amp;GlobalDateFormat(@DTTO@)</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>17</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1199707382</id>
    <cell_text>=Bold(''Transaction Type : '')&amp;@ApprvTrnxType@&amp;Bold(''  | Site Name : '')&amp;@SiteName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>17</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>72923121</id>
    <cell_text>Entry Module</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2075319507</id>
    <cell_text>Requested By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2122024842</id>
    <cell_text>Requested On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>410740746</id>
    <cell_text>Entry No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1595111016</id>
    <cell_text>Entry Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1077245412</id>
    <cell_text>Entry Site</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>698760780</id>
    <cell_text>Seq No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1706081254</id>
    <cell_text>Rule Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1373534582</id>
    <cell_text>Priority</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1558836994</id>
    <cell_text>Quorum Required</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>362702009</id>
    <cell_text>Level No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>943424846</id>
    <cell_text>Level Label</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>904452348</id>
    <cell_text>Actived On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1179298796</id>
    <cell_text>Escalated On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>13</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>250740594</id>
    <cell_text>Reminder Count</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>14</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>775034135</id>
    <cell_text>Last Reminded On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1649768937</id>
    <cell_text>Pending From</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>563106836</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_module</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>2073038051</id>
    <cell_text>LV_APPRV_DOC_INST_01.requested_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1579137238</id>
    <cell_text>LV_APPRV_DOC_INST_01.requested_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1246454132</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1158215331</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1043540597</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_site</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1379009985</id>
    <cell_text>LV_APPRV_DOC_INST_01.seq_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>1819912371</id>
    <cell_text>LV_APPRV_DOC_INST_01.rule_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>945638753</id>
    <cell_text>LV_APPRV_DOC_INST_01.priority</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <background_color>#F5F5F5</background_color>
  </cell>
  <cell>
    <id>872105950</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>9</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>LineNumberWithReset({LV_APPRV_DOC_INST_01.entry_module}&amp;{LV_APPRV_DOC_INST_01.requested_on}&amp;{LV_APPRV_DOC_INST_01.requested_by}&amp;{LV_APPRV_DOC_INST_01.entry_date}&amp;{LV_APPRV_DOC_INST_01.entry_no}&amp;{LV_APPRV_DOC_INST_01.entry_site}&amp;{LV_APPRV_DOC_INST_01.rule_name}&amp;{LV_APPRV_DOC_INST_01.seq_no}&amp;{LV_APPRV_DOC_INST_01.priority},''sl'')&gt;1</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>130772569</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_module</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1196908747</id>
    <cell_text>LV_APPRV_DOC_INST_01.requested_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>2093121814</id>
    <cell_text>LV_APPRV_DOC_INST_01.requested_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1444166019</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>822482094</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1163426463</id>
    <cell_text>LV_APPRV_DOC_INST_01.entry_site</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1569757158</id>
    <cell_text>LV_APPRV_DOC_INST_01.seq_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>51553779</id>
    <cell_text>LV_APPRV_DOC_INST_01.rule_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>788163724</id>
    <cell_text>LV_APPRV_DOC_INST_01.priority</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1043584663</id>
    <cell_text>LV_APPRV_DOC_LEVEL_01.quorum_req</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>391415485</id>
    <cell_text>LV_APPRV_DOC_LEVEL_01.level_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1558881839</id>
    <cell_text>LV_APPRV_DOC_LEVEL_01.level_label</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>611913588</id>
    <cell_text>LV_APPRV_DOC_LEVEL_01.activated_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1602899469</id>
    <cell_text>LV_APPRV_DOC_LEVEL_01.escalated_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>13</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1063865610</id>
    <cell_text>LV_APPRV_DOC_TASK_01.reminder_count</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>14</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1489546688</id>
    <cell_text>LV_APPRV_DOC_TASK_01.last_reminded_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>632899748</id>
    <cell_text>LV_APPRV_DOC_TASK_01.approved_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>952059684</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateTimeFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>516898318</id>
    <cell_text>=''Page No. : ''&amp;PageNumber()</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1481824468</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1120993078</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2091042524</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>395073897</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>759725734</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>985815044</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>842151901</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2028547589</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Detail</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>111</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>115</column_width>
  </column>
  <column>
    <column_width>143</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>200</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_APPRV_DOC_INST_01</entity_from_name>
    <entity_to_name>LV_APPRV_DOC_LEVEL_01</entity_to_name>
    <entity_from_id>LV_APPRV_DOC_INST_01</entity_from_id>
    <entity_to_id>LV_APPRV_DOC_LEVEL_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>1M</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>instcode</col_from_name>
      <col_to_name>instcode</col_to_name>
    </key>
    <clause>
      <left_side>instcode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>instcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_APPRV_DOC_LEVEL_01</entity_from_name>
    <entity_to_name>LV_APPRV_DOC_TASK_01</entity_to_name>
    <entity_from_id>LV_APPRV_DOC_LEVEL_01</entity_from_id>
    <entity_to_id>LV_APPRV_DOC_TASK_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>1M</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>instcode</col_from_name>
      <col_to_name>instcode</col_to_name>
    </key>
    <key>
      <col_from_name>level_code</col_from_name>
      <col_to_name>level_code</col_to_name>
    </key>
    <clause>
      <left_side>instcode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>instcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
    <clause>
      <left_side>level_code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>level_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.entry_module</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.requested_on</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.requested_by</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.entry_date</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.entry_no</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.seq_no</sort_name>
    <sort_title />
    <order_num>5</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.rule_name</sort_name>
    <sort_title />
    <order_num>6</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_INST_01.priority</sort_name>
    <sort_title />
    <order_num>7</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_LEVEL_01.quorum_req</sort_name>
    <sort_title />
    <order_num>8</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_APPRV_DOC_LEVEL_01.level_no</sort_name>
    <sort_title />
    <order_num>9</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_APPRV_DOC_INST_01.entry_no</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1317439277</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_APPRV_DOC_INST_01.requested_by</filter_name>
    <order_num>1</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1330160209</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_APPRV_DOC_INST_01.requested_on</filter_name>
    <order_num>2</order_num>
    <operator>bt</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>2145263271</filter_ref_id>
    <filter_title />
    <values>
      <value>@DTFR@</value>
    </values>
    <values>
      <value>@DTTO@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_APPRV_DOC_INST_01.entry_module</filter_name>
    <order_num>3</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1799015797</filter_ref_id>
    <filter_title />
    <values>
      <value>@ApprvTrnxType@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_APPRV_DOC_INST_01.entry_site_code</filter_name>
    <order_num>4</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1306171589</filter_ref_id>
    <filter_title />
    <values>
      <value>@SiteName@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>asc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2026-09-23 13:09:35.510857', '2275', '2026-09-24 06:54:54.358646',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 25,
    FALSE, 2, 832,
    NULL, 16, 0,
    FALSE, FALSE, NULL,
    NULL, '2026010', 'I'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '2f255744-ca2d-4922-9e96-569b391fdb21', 'e17500c1-bfbc-495a-af33-62edc414e1ec', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026010', 'I'
);
