-- =====================================================
-- INSERT statement for content_id: e5340650-d9d1-481e-9ae4-e7b08edaf63d
-- Name: #Purchase Return#
-- Action: UPDATE
-- Version: 2026008
-- Generated on: 2026-09-18 15:24:40
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    'e5340650-d9d1-481e-9ae4-e7b08edaf63d', 0, 0,
    NULL, '#Purchase Return#', NULL,
    '<report>
  <main>
    <id>e5340650-d9d1-481e-9ae4-e7b08edaf63d</id>
    <report_name>#Purchase Return#</report_name>
    <folder_name>Procurement\Documents</folder_name>
    <folder_id>f4cb3979-6522-473b-9406-f3be215245a0</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>4,1,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description />
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>True</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>RQ_PURRET_DOC_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>Report Specific|*{*}*|Document|*{*}*|Purchase Return</category>
  </entity>
  <cell>
    <id>1182169988</id>
    <cell_text>=If(@PrintLogo@=''Y'', OULogo(), '''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_rowspan>9</cell_rowspan>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>275086635</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_refsite_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>0</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>624752741</id>
    <cell_text>Purchase Return</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>917267308</id>
    <cell_text>={RQ_PURRET_DOC_01.l1_header_refsite_address}&amp;'', ''&amp;{RQ_PURRET_DOC_01.l1_header_refsite_city}&amp;'', ''&amp;{RQ_PURRET_DOC_01.l1_header_refsite_pincode}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>44916870</id>
    <cell_text>=QrCodeXzing({RQ_PURRET_DOC_01.l1_header_e_invoice_signed_qr_data})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>9</cell_col>
    <cell_rowspan>8</cell_rowspan>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>Contains(CellValue(), ''error'')</formula>
      <action>ForegroundColor</action>
      <attribute>#FFFFFF</attribute>
    </conditional>
  </cell>
  <cell>
    <id>1607464199</id>
    <cell_text>=''Phone : ''&amp; {RQ_PURRET_DOC_01.l1_header_refsite_phone1}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2000543442</id>
    <cell_text>=''Email Id : ''&amp;{RQ_PURRET_DOC_01.l1_header_owner_site_email2}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1242763023</id>
    <cell_text>=''Website : ''&amp;{RQ_PURRET_DOC_01.l1_header_owner_site_website}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>874140433</id>
    <cell_text>=''GSTIN : ''&amp;{RQ_PURRET_DOC_01.l1_header_refsite_gstin_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2052497719</id>
    <cell_text>=If({RQ_PURRET_DOC_01.l1_header_refsite_gstin_no}='''', '''', ''GST State : ''&amp;{RQ_PURRET_DOC_01.l1_header_refsite_gst_state_name}&amp;''(''&amp;{RQ_PURRET_DOC_01.l1_header_refsite_gst_state_code}&amp;'')'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>756721258</id>
    <cell_text>=''CIN : ''&amp;@ConnOUCINNo@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1403368100</id>
    <cell_text>=''Invoice No. : ''&amp;{RQ_PURRET_DOC_01.l1_header_return_invoice_no}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2020259141</id>
    <cell_text>=''Date : ''&amp;GlobalDateFormat({RQ_PURRET_DOC_01.l1_header_purchase_return_date})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1126795559</id>
    <cell_text>Supplier Name :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1566787195</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_cust_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>244818502</id>
    <cell_text>Document No. :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>165237428</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_document_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>543617194</id>
    <cell_text>Supplier Address :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>11</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>488245529</id>
    <cell_text>={RQ_PURRET_DOC_01.l1_header_cust_billing_address}&amp;'', ''&amp;{RQ_PURRET_DOC_01.l1_header_cust_billing_city}&amp;'', ''&amp;{RQ_PURRET_DOC_01.l1_header_cust_billing_pincode}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1381293229</id>
    <cell_text>Logistic No :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>11</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1477087856</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_logistic_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>331252638</id>
    <cell_text>Logistic Date :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>653474797</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_logistic_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1549027841</id>
    <cell_text>Supplier Contact :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1931151660</id>
    <cell_text>={RQ_PURRET_DOC_01.l1_header_cust_billing_office_phone1}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1840508401</id>
    <cell_text>Lgt. Decl. Amt. :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1715221296</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_logistic_declared_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1728320892</id>
    <cell_text>Supplier Email :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>396586688</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_cust_billing_email1</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>979182823</id>
    <cell_text>Agent Name :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>513822908</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_agent_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>521043927</id>
    <cell_text>GSTIN :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1483685482</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_cust_gstin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>15</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1772649339</id>
    <cell_text>Agent Rate :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1758705951</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_agent_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>15</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>2019143174</id>
    <cell_text>GST State :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1277440192</id>
    <cell_text>=If({RQ_PURRET_DOC_01.l1_header_cust_gstin_no}='''', '''', {RQ_PURRET_DOC_01.l1_header_cust_gst_state_name}&amp;''(''&amp;{RQ_PURRET_DOC_01.l1_header_cust_gst_state_code}&amp;'')'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>16</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1663327430</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1630356725</id>
    <cell_text>Group/Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1098728558</id>
    <cell_text>HSN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>767429822</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>330365062</id>
    <cell_text>Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2076788711</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2136522738</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1817898459</id>
    <cell_text>={RQ_PURRET_DOC_01.l2_detail_section}&amp;'' - ''&amp;{RQ_PURRET_DOC_01.l2_detail_department}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <conditional>
      <formula>CellValue()='' - ''</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1003916110</id>
    <cell_text>=LineNumberWithReset({RQ_PURRET_DOC_01.l1_header_rtcode}&amp;{RQ_PURRET_DOC_01.l2_detail_section}&amp;{RQ_PURRET_DOC_01.l2_detail_department},''sl'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <foreground_color>#FFFFFF</foreground_color>
    <conditional>
      <formula>CellValue()&gt;1</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>990252171</id>
    <cell_text>RQ_PURRET_DOC_01.l2_detail_item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <conditional>
      <formula>CellValue()=''------''</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>66560459</id>
    <cell_text>RQ_PURRET_DOC_01.l2_detail_hsn_sac_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>19</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1058453007</id>
    <cell_text>RQ_PURRET_DOC_01.l2_detail_return_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>19</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>120854958</id>
    <cell_text>RQ_PURRET_DOC_01.l2_detail_return_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>19</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>246117400</id>
    <cell_text>RQ_PURRET_DOC_01.l2_detail_uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>19</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>29741912</id>
    <cell_text>=[G20]*[I20]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1343829814</id>
    <cell_text>=If({item_management_mode}=''B'', ''Batch : ''&amp;{RQ_PURRET_DOC_01.l2_detail_batch_serial_string}, ''Serial : ''&amp;{RQ_PURRET_DOC_01.l2_detail_batch_serial_string})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>20</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_italic_flag>True</font_italic_flag>
    <foreground_color>#9F9F9F</foreground_color>
    <conditional>
      <formula>Or([B21]=''Batch : '',[B21]=''Serial : '')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>422889040</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1702791015</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2123250180</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>564259956</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1194042927</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>372402913</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1141183273</id>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1554242802</id>
    <cell_text>=aggsum([I20])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1582037233</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1214502305</id>
    <cell_text>=aggsum([K20])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>8</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1614139854</id>
    <cell_text>RQ_PURRET_DOC_01.l3_charge_charge_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>23</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1381524899</id>
    <cell_text>=If({RQ_PURRET_DOC_01.l3_charge_charge_basis}=''Amount'', ''@''&amp;VALUE({RQ_PURRET_DOC_01.l3_charge_charge_rate})&amp;'' On ''&amp;VALUE({RQ_PURRET_DOC_01.l3_charge_charge_applicable_on}), ''@''&amp;VALUE({RQ_PURRET_DOC_01.l3_charge_charge_rate})&amp;''% On ''&amp;VALUE({RQ_PURRET_DOC_01.l3_charge_charge_applicable_on}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>23</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>319267999</id>
    <cell_text>RQ_PURRET_DOC_01.l3_charge_charge_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>23</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <format_negative_color>#FFFFFF</format_negative_color>
    <conditional>
      <formula>{RQ_PURRET_DOC_01.seq}!=2</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1805870140</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1512864425</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1557160154</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1282859924</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1482909840</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>279589641</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1689390960</id>
    <cell_text>Grand Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1341453837</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1617707389</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>213269613</id>
    <cell_text>RQ_PURRET_DOC_01.l1_header_net_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>24</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1501264798</id>
    <cell_text>=''Amount In Words : ''&amp;AmountinWords({RQ_PURRET_DOC_01.l1_header_net_amount})&amp;'' Only.''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>25</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1620715471</id>
    <cell_text>Goods Return No. &amp; Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2013070147</id>
    <cell_text>Goods Receive No. &amp; Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1060081681</id>
    <cell_text>Purchase Invoice &amp; Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>625628809</id>
    <cell_text>Supplier Document &amp; Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>26</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>791056680</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_grt_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>68092086</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_grt_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>515902622</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_grc_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1363955948</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_grc_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>337073137</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_invoice_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>6</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>693666189</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_invoice_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>730577726</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_invoice_document_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1573988329</id>
    <cell_text>RQ_PURRET_DOC_01.l5_refdoc_invoice_document_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>27</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1960546764</id>
    <cell_text>HSN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>183510125</id>
    <cell_text>Taxable Value</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>915780241</id>
    <cell_text>Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>259862374</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1902451501</id>
    <cell_text>CGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>356861924</id>
    <cell_text>SGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1931220687</id>
    <cell_text>IGST</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>339925851</id>
    <cell_text>CESS</cell_text>
    <cell_type>text</cell_type>
    <cell_row>29</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>106544324</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>858217863</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>60767341</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>956020240</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>22698356</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>997018612</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>310931828</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1390994677</id>
    <cell_text>Amt</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1767081809</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_hsn_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>927788569</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_taxable_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1669327737</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_return_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>986355677</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1052666829</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_cgst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1818982863</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_cgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>676975604</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_sgst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>412209337</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_sgst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1752545968</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_igst_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1658668067</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_igst_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1909412597</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_cess_rate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_right_width>1</border_right_width>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1376050049</id>
    <cell_text>RQ_PURRET_DOC_01.l4_hsn_cess_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>31</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1313187875</id>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>2079933599</id>
    <cell_text>=aggsum([B32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>131479652</id>
    <cell_text>=aggsum([C32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>176494061</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>785791986</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>93163048</id>
    <cell_text>=aggsum([F32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1301921228</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>290173214</id>
    <cell_text>=aggsum([H32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>294535141</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>266671158</id>
    <cell_text>=aggsum([J32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>83891888</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>32</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>1387732631</id>
    <cell_text>=aggsum([L32])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>11</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#DFDFDF</background_color>
  </cell>
  <cell>
    <id>758590613</id>
    <cell_text>=If({RQ_PURRET_DOC_01.l1_header_remarks}='''', '''', ''Remarks : ''&amp;{RQ_PURRET_DOC_01.l1_header_remarks})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>34</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1441972052</id>
    <cell_text>=''For ''&amp;@ConnOUName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>35</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>295409368</id>
    <cell_text>Prepared By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>726593264</id>
    <cell_text>Checked By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>764422593</id>
    <cell_text>Delivered By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>674852905</id>
    <cell_text>Authorized Signatory</cell_text>
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>968622292</id>
    <cell_text>={RQ_PURRET_DOC_01.l1_header_created_by}&amp;NewLine()&amp;GlobalDateFormat({RQ_PURRET_DOC_01.l1_header_created_on})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>39</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>103655074</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>40</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1395284276</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>80806438</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1157373157</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>928702003</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>824723342</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>40</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>934589353</id>
    <cell_text>=''Page No. : ''&amp;PageNoWithReset({RQ_PURRET_DOC_01.l1_header_rtcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>40</cell_row>
    <cell_col>9</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <pagebreak_flag>True</pagebreak_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_PURRET_DOC_01.l1_header_rtcode</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <sort>
    <sort_name>RQ_PURRET_DOC_01.l1_header_rtcode</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_PURRET_DOC_01.seq</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_PURRET_DOC_01.lvl</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>={RQ_PURRET_DOC_01.l2_detail_section}&amp;'' - ''&amp;{RQ_PURRET_DOC_01.l2_detail_department}</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_PURRET_DOC_01.l2_detail_batch_serial_string</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>RQ_PURRET_DOC_01.l1_header_rtcode</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1440280724</filter_ref_id>
    <filter_title />
    <values>
      <value>@DocumentId@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>asc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2023-01-31 11:42:36', '1295', '2026-09-10 10:18:45.228970',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 3,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026008', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    'e5340650-d9d1-481e-9ae4-e7b08edaf63d', '0120d4fa-dcf0-4eb8-a07d-c883f734e4cd', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026008', 'U'
);
