-- =====================================================
-- INSERT statement for content_id: 8cbb76f9-cd4b-4b2f-bf4d-7e42aa71ba81
-- Name: #Inter Location Transfer#
-- Action: UPDATE
-- Version: 2026008
-- Generated on: 2026-09-22 14:24:38
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '8cbb76f9-cd4b-4b2f-bf4d-7e42aa71ba81', 0, 0,
    NULL, '#Inter Location Transfer#', 'This is a Stock Point Transfer (Inter Location Transfer) Document Report, to be used for document printing purpose. Should be executed from Stock Point Transfer Transaction only.',
    '<report>
  <main>
    <id>8cbb76f9-cd4b-4b2f-bf4d-7e42aa71ba81</id>
    <report_name>#Inter Location Transfer#</report_name>
    <folder_name>Inventory\Documents</folder_name>
    <folder_id>3942da7c-bf44-4c44-8eff-f42cf75a97b2</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output>4,1,3</prevent_output>
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This is a Stock Point Transfer (Inter Location Transfer) Document Report, to be used for document printing purpose. Should be executed from Stock Point Transfer Transaction only.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>True</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>-1</row_range_limit>
  </main>
  <entity>
    <entity_name>RQ_INTER_STOCK_TRANSFER_DOC_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>Report Specific|*{*}*|Document|*{*}*|Inter Location Transfer</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>738726035</id>
    <cell_text>@ExecutingSQL@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>27</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>911216230</id>
    <cell_text>=If(@PrintLogo@=''Y'', OULogo(), '''')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>10164398</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>1</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>265771811</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1896746769</id>
    <cell_text>=If(@ReportTitle@!='''', @ReportTitle@, ''Inter Location Transfer Note'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>22</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>21</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>14</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>494450868</id>
    <cell_text>LV_SITE_01.address</cell_text>
    <cell_type>data</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>805741887</id>
    <cell_text>={LV_SITE_01.phone1}&amp;'' ''&amp;{LV_SITE_01.phone2}&amp;'' ''&amp;{LV_SITE_01.phone3}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1810355412</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>26</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>607609555</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>30</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1019427111</id>
    <cell_text>={LV_SITE_01.email1}&amp;If({LV_SITE_01.email1}!='''', '', ''&amp;{LV_SITE_01.email2}, {LV_SITE_01.email2})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>16</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>197485729</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>16</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>114290921</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>26</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1527659681</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>30</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2066437731</id>
    <cell_text>={LV_SITE_01.website}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1661927977</id>
    <cell_text>CIN No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1095671552</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1050693414</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.orgunit_cin</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>2083993391</id>
    <cell_text>Transfer No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>28</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>885516573</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>33</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>124781949</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.transfer_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1882327374</id>
    <cell_text>GSTIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>1106419357</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>46597585</id>
    <cell_text>={LV_SITE_01.gst_identification_no}&amp; ''[''&amp;{LV_SITE_01.gst_state_code}&amp;'' -''&amp;{LV_SITE_01.gst_state_name}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
  </cell>
  <cell>
    <id>706081411</id>
    <cell_text>Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>28</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1278917198</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>33</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1719155638</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.transfer_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>34</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1468304945</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>43</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1118831113</id>
    <cell_text>Group / Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
    <conditional>
      <formula>If(LineNumberWithReset({RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode},''header'')=1, ''True'', ''False'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>252678819</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>14</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>982255890</id>
    <cell_text>Transfer Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>96339400</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>474086751</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>27</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>878403384</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>30</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2077910856</id>
    <cell_text>Transfer Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>895610391</id>
    <cell_text>RSP Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1968357608</id>
    <cell_text>From</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2102922148</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1861785353</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.out_stockpoint_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>650684843</id>
    <cell_text>Gate Entry No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <border_top_width>1</border_top_width>
    <border_left_width>1</border_left_width>
    <border_top_color>#000000</border_top_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>997220078</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1107174835</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.gate_entry_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>634726929</id>
    <cell_text>GSTIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1705754422</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1656915836</id>
    <cell_text>LV_SITE_01.gst_identification_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>451570035</id>
    <cell_text>Document No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>2121530437</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1590895237</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.document_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>789730810</id>
    <cell_text>GST State</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>66487695</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1655057991</id>
    <cell_text>={LV_SITE_01.gst_state_name}&amp;''(''&amp;{LV_SITE_01.gst_state_code}&amp;'')''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>710503096</id>
    <cell_text>Document Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>2087654745</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1584705656</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.document_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>14</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1518828645</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>126398734</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>5</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1910575982</id>
    <cell_text>Logistic No</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>919411301</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>15</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>208415063</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.out_logistic_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>15</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1881876412</id>
    <cell_text>To</cell_text>
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>67003728</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1124280589</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.in_stockpoint_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>16</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1232053519</id>
    <cell_text>Logistic Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>1195929957</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>16</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>521709211</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.out_logistic_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>16</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1437667514</id>
    <cell_text>GSTIN</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1657148941</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>142419684</id>
    <cell_text>LV_SITE_01.gst_identification_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>17</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2018440081</id>
    <cell_text>Declared Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>23</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_left_width>1</border_left_width>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>253208127</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>29</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1282679289</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.out_logistic_declared_amount</cell_text>
    <cell_type>data</cell_type>
    <cell_row>17</cell_row>
    <cell_col>30</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>577429925</id>
    <cell_text>GST State</cell_text>
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2053146272</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>717226696</id>
    <cell_text>={LV_SITE_01.gst_state_name}&amp;''(''&amp;{LV_SITE_01.gst_state_code}&amp;'')''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>18</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>18</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>690715025</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>23</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>899430425</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>601543239</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>391400651</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1655036669</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>27</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>316896011</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>28</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>236902563</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>29</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1207390853</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>30</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2090526349</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>31</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>17407193</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>32</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1794812660</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>33</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1827890341</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>34</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>120038473</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>35</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>543798021</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>18</cell_row>
    <cell_col>36</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1139344381</id>
    <cell_text>@ReportHeader@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>37</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>687520542</id>
    <cell_text>Group / Item</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>14</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1750689249</id>
    <cell_text>HSN Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>14</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>924099623</id>
    <cell_text>Transfer Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1312383053</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1458689047</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>27</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>844041380</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>30</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1027806225</id>
    <cell_text>Transfer Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1976586035</id>
    <cell_text>RSP Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>20</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1201101490</id>
    <cell_text>={RQ_INTER_STOCK_TRANSFER_DOC_01.detail_section}&amp;'' - ''&amp;{RQ_INTER_STOCK_TRANSFER_DOC_01.detail_department}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>12</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <conditional>
      <formula>If(CellValue() = '' - '',''true'',''false'') </formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>957092473</id>
    <cell_text>=LineNumberWithReset({RQ_INTER_STOCK_TRANSFER_DOC_01.detail_section}&amp;{RQ_INTER_STOCK_TRANSFER_DOC_01.detail_department},''Assembly'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>12</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#FFFFFF</foreground_color>
    <conditional>
      <formula>If(CellValue() &gt; 1,''true'',''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1910430159</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>24</cell_col>
    <cell_colspan>13</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1541643363</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_barcode</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <conditional>
      <formula>If({RQ_INTER_STOCK_TRANSFER_DOC_01.quantity}=Null(), ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1157902578</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>11</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <conditional>
      <formula>If(CellValue()='' '', ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>235090108</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_item_hsn_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>14</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1587253496</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.stfrate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1552040551</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_rsp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>24</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>464883367</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>27</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1691970898</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>22</cell_row>
    <cell_col>30</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>66897397</id>
    <cell_text>={RQ_INTER_STOCK_TRANSFER_DOC_01.stfrate}*{RQ_INTER_STOCK_TRANSFER_DOC_01.quantity}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>22</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>833389850</id>
    <cell_text>={RQ_INTER_STOCK_TRANSFER_DOC_01.quantity}*{RQ_INTER_STOCK_TRANSFER_DOC_01.detail_rsp}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>22</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <format_negative_color>#FFFFFF</format_negative_color>
  </cell>
  <cell>
    <id>1355766181</id>
    <cell_text>=If({RQ_INTER_STOCK_TRANSFER_DOC_01.detail_item_management_mode}=''B'', ''Batch : ''&amp;{RQ_INTER_STOCK_TRANSFER_DOC_01.batch_serial_string}, ''Serial : ''&amp;{RQ_INTER_STOCK_TRANSFER_DOC_01.batch_serial_string})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>23</cell_row>
    <cell_col>3</cell_col>
    <cell_colspan>40</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <foreground_color>#9F9F9F</foreground_color>
    <conditional>
      <formula>Or([D24]=''Batch : '',[D24]=''Serial : '')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>1153488230</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>24870371</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>719986695</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2062185935</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>7</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>889211532</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>9</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1370915527</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>526115720</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>986974365</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>13</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>974998925</id>
    <cell_text>Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>21</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>129994802</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>901519065</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>356909899</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>893973222</id>
    <cell_text>=AggSum({RQ_INTER_STOCK_TRANSFER_DOC_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>27</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>177126506</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>30</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1016227287</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>24</cell_row>
    <cell_col>31</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>517190178</id>
    <cell_text>=AggSum([AG23])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>32</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>716893671</id>
    <cell_text>=AggSum([AM23])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>24</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>77896338</id>
    <cell_text>Amount in Words</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1084323638</id>
    <cell_text>:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>25</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>879021056</id>
    <cell_text>='' ''&amp;AmountinWords([AM25])&amp;'' Only''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>25</cell_row>
    <cell_col>8</cell_col>
    <cell_colspan>35</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>725061222</id>
    <cell_text>Remarks</cell_text>
    <cell_type>text</cell_type>
    <cell_row>27</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <font_underline_flag>True</font_underline_flag>
    <font_underline_style>Single</font_underline_style>
    <conditional>
      <formula>If({RQ_INTER_STOCK_TRANSFER_DOC_01.remarks}='''', ''true'', ''false'')</formula>
      <action>SuppressRow</action>
    </conditional>
  </cell>
  <cell>
    <id>831153337</id>
    <cell_text>RQ_INTER_STOCK_TRANSFER_DOC_01.remarks</cell_text>
    <cell_type>data</cell_type>
    <cell_row>28</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>37</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1717190652</id>
    <cell_text>@ReportFooter@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>30</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>37</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1826137905</id>
    <cell_text>=''For ''&amp;@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>32</cell_row>
    <cell_col>35</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1460955675</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>34</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1538265208</id>
    <cell_text>Prepared By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>35</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>80589526</id>
    <cell_text>Checked By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>35</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>135908859</id>
    <cell_text> Passed By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>35</cell_row>
    <cell_col>35</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1151601768</id>
    <cell_text>={RQ_INTER_STOCK_TRANSFER_DOC_01.created_by}&amp;'' On ''&amp;GlobalDateFormat({RQ_INTER_STOCK_TRANSFER_DOC_01.creation_time})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>36</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1010652164</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1590101676</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>11</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1957263488</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>24</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1263359606</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>38</cell_row>
    <cell_col>30</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1765375098</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>39</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>606568873</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>10</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>215572225</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>14</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>372938748</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1983101143</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1272234075</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>61840367</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>238265919</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>19</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1807359673</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>20</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1533418035</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>21</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1476701504</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>22</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2042019014</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>23</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1173873412</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>24</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>465908516</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>25</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2076317776</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>26</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1823593608</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>27</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1921100218</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>28</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1960364432</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>29</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>675124814</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>30</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1092147164</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>31</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1812417735</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>32</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>80627444</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>33</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1626581731</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>34</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1388772919</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>35</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>360524953</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>36</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1516782483</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>39</cell_row>
    <cell_col>37</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1700923392</id>
    <cell_text>=''Page :  ''&amp;PageNoWithReset({RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>39</cell_row>
    <cell_col>38</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <row_height>4</row_height>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
    <pagebreak_flag>True</pagebreak_flag>
    <row_height>1</row_height>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
    <subreport_start_flag>True</subreport_start_flag>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
    <subreport_end_flag>True</subreport_end_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
    <row_height>5</row_height>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
    <row_height>5</row_height>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>150</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>RQ_INTER_STOCK_TRANSFER_DOC_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>RQ_INTER_STOCK_TRANSFER_DOC_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_section</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_department</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_INTER_STOCK_TRANSFER_DOC_01.detail_barcode</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>RQ_INTER_STOCK_TRANSFER_DOC_01.batch_serial_string</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>RQ_INTER_STOCK_TRANSFER_DOC_01.stfcode</filter_name>
    <order_num>0</order_num>
    <operator>oo</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1629249849</filter_ref_id>
    <filter_title />
    <values>
      <value>@DocumentId@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2021-02-09 16:47:03', '1300', '2026-09-22 08:14:35.508538',
    '2274', '75a16cac-c843-4b39-8259-a06b6f97fea3', 3,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026008', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '8cbb76f9-cd4b-4b2f-bf4d-7e42aa71ba81', '1157ccb6-852a-4e1c-98d7-310e410c97ab', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026008', 'U'
);
