-- =====================================================
-- INSERT statement for content_id: 0cbde004-431c-4a0a-a8af-d9bd87d51f8d
-- Name: #Reservation Register#
-- Action: UPDATE
-- Version: 2026004
-- Generated on: 2026-06-16 16:00:03
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '0cbde004-431c-4a0a-a8af-d9bd87d51f8d', 0, 0,
    NULL, '#Reservation Register#', 'This report will show Reservation details along with Order information whenever is applicable',
    '<report>
  <main>
    <id>0cbde004-431c-4a0a-a8af-d9bd87d51f8d</id>
    <report_name>#Reservation Register#</report_name>
    <folder_name>Inventory\Register</folder_name>
    <folder_id>c55b7299-0a15-4662-bb70-cdc244f1c79d</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will show Reservation details along with Order information whenever is applicable</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_02</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_STOCK_RESERVATION_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|02-Transaction|*{*}*|WMS</category>
  </entity>
  <cell>
    <id>1455398277</id>
    <cell_text>=@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>30494683</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>269032628</id>
    <cell_text>=Bold(''Period : '')&amp;GlobalDateFormat(@DTFR@)&amp;Bold('' To : '')&amp;GlobalDateFormat(@DTTO@)</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1108858666</id>
    <cell_text>Reservation Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>825596901</id>
    <cell_text>Reservation No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1001578128</id>
    <cell_text>Source Order Type</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1551572141</id>
    <cell_text>Order No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>115906242</id>
    <cell_text>Order Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>329336722</id>
    <cell_text>Owner Site</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1280280753</id>
    <cell_text>Channel</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1281078054</id>
    <cell_text>Pick List Rule</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>693522002</id>
    <cell_text>Reference SIte</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>661358496</id>
    <cell_text>Bin No.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1097948457</id>
    <cell_text>ICODE</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1711003142</id>
    <cell_text>Item Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1269923549</id>
    <cell_text>Reserved Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1803686794</id>
    <cell_text>Cancelled Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>303424</id>
    <cell_text>Pick List Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1238056536</id>
    <cell_text>Created By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>15</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1787426323</id>
    <cell_text>Created On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>16</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>98950477</id>
    <cell_text>Last Modified By</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>17</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1926704698</id>
    <cell_text>Last Modified On</cell_text>
    <cell_type>text</cell_type>
    <cell_row>3</cell_row>
    <cell_col>18</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1242971468</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>345324826</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1571019328</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>604008807</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_type</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2101737736</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1827708010</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1149804713</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1970353693</id>
    <cell_text>LV_STOCK_RESERVATION_01.channel_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>146166337</id>
    <cell_text>LV_STOCK_RESERVATION_01.pick_list_rule</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>353440946</id>
    <cell_text>LV_SITE_02.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>482494685</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1153714446</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>137417376</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modified_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>17</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>305455037</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modifed_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>5</cell_row>
    <cell_col>18</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1505533110</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1181063159</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>936631375</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_type</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>330826691</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1175547076</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>683485433</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>644377983</id>
    <cell_text>LV_STOCK_RESERVATION_01.channel_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>957279087</id>
    <cell_text>LV_STOCK_RESERVATION_01.pick_list_rule</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1238077613</id>
    <cell_text>LV_SITE_02.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1801830277</id>
    <cell_text>LV_STOCK_RESERVATION_01.bin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>785627766</id>
    <cell_text>=[M11]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>172646744</id>
    <cell_text>=[N11]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>735801118</id>
    <cell_text>=[O11]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>6</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>537259425</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1125856341</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>842024865</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modified_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>17</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1477380689</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modifed_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>18</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>2083252523</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>429465723</id>
    <cell_text>LV_STOCK_RESERVATION_01.reservation_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1106640200</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_type</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1547754503</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1595620484</id>
    <cell_text>LV_STOCK_RESERVATION_01.order_date</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1006695806</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>852746179</id>
    <cell_text>LV_STOCK_RESERVATION_01.channel_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1273188858</id>
    <cell_text>LV_STOCK_RESERVATION_01.pick_list_rule</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>2041282159</id>
    <cell_text>LV_SITE_02.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1388090033</id>
    <cell_text>LV_STOCK_RESERVATION_01.bin_no</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
  </cell>
  <cell>
    <id>1807180120</id>
    <cell_text>=If({LV_ITEM_01.barcode}='''',{LV_STOCK_RESERVATION_01.icode}, {LV_ITEM_01.barcode})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>331501004</id>
    <cell_text>LV_ITEM_01.item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2069584532</id>
    <cell_text>=[M10]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>490867413</id>
    <cell_text>=[N10]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>145113309</id>
    <cell_text>=[O10]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1589151193</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>15</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1828959891</id>
    <cell_text>LV_STOCK_RESERVATION_01.created_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>16</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>409334615</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modified_by</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>17</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>328653773</id>
    <cell_text>LV_STOCK_RESERVATION_01.last_modifed_on</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>18</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <foreground_color>#9F9F9F</foreground_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2126110590</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.reserved_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2071170603</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.cancelled_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>446312818</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.pick_list_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1171589762</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.pick_list_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2005135311</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.reserved_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>797814019</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.cancelled_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>277554636</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.pick_list_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>888936087</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.reserved_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2058208142</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.cancelled_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>712235203</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.pick_list_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>751125425</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.reserved_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1145750147</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.cancelled_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1432941795</id>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1693296507</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1537266387</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1828630694</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>754244918</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>829982435</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1511448399</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1261122623</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1415699862</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.pick_list_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1897799357</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.reserved_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>12</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1099500470</id>
    <cell_text>=aggsum({LV_STOCK_RESERVATION_01.cancelled_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1045517519</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>306388188</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1696624468</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1864060871</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>549056611</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>14</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>668938772</id>
    <cell_text>=''Page No. : ''&amp;PageNumber()</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>10</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>10</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STOCK_RESERVATION_01.reservation_date</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STOCK_RESERVATION_01.reservation_no</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STOCK_RESERVATION_01.bin_no</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STOCK_RESERVATION_01.icode</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STOCK_RESERVATION_01.icode</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STOCK_RESERVATION_01.bin_no</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STOCK_RESERVATION_01.reservation_no</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STOCK_RESERVATION_01.reservation_date</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>115</column_width>
  </column>
  <column>
    <column_width>141</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>197</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>200</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>218</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>15</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_STOCK_RESERVATION_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_STOCK_RESERVATION_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_02</entity_from_name>
    <entity_to_name>LV_STOCK_RESERVATION_01</entity_to_name>
    <entity_from_id>LV_SITE_02</entity_from_id>
    <entity_to_id>LV_STOCK_RESERVATION_01</entity_to_id>
    <join_type>rightouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_STOCK_RESERVATION_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_STOCK_RESERVATION_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code_owner</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code_owner</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_STOCK_RESERVATION_01.reservation_date</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STOCK_RESERVATION_01.reservation_no</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STOCK_RESERVATION_01.bin_no</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STOCK_RESERVATION_01.icode</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_STOCK_RESERVATION_01.reservation_date</filter_name>
    <order_num>0</order_num>
    <operator>bt</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1305267451</filter_ref_id>
    <filter_title />
    <values>
      <value>@DTFR@</value>
    </values>
    <values>
      <value>@DTTO@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_SITE_01.name</filter_name>
    <order_num>1</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>964793420</filter_ref_id>
    <filter_title>Owner Site</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_SITE_02.name</filter_name>
    <order_num>2</order_num>
    <operator>oo</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>134306834</filter_ref_id>
    <filter_title>Reference Site</filter_title>
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_STOCK_RESERVATION_01.order_code</filter_name>
    <order_num>3</order_num>
    <operator>&gt;</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>617794758</filter_ref_id>
    <filter_title />
    <values>
      <value>0</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>asc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2022-03-03 10:01:36', '1295', '2026-06-16 10:25:47.733270',
    '132560', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026004', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '0cbde004-431c-4a0a-a8af-d9bd87d51f8d', '8ee7e5fe-12b9-4212-951a-82008c8603d0', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026004', 'U'
);
