-- =====================================================
-- INSERT statement for content_id: 018545b0-2b8a-4826-bdd2-fb07a6732a40
-- Name: #VMI Sale (Retail) Register#
-- Action: UPDATE
-- Version: 2026004
-- Generated on: 2026-07-08 16:26:16
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '018545b0-2b8a-4826-bdd2-fb07a6732a40', 0, 0,
    NULL, '#VMI Sale (Retail) Register#', 'This report will display Sale (Retail) of the item(s) of the selected Vendor for last 60 days				',
    '<report>
  <main>
    <id>018545b0-2b8a-4826-bdd2-fb07a6732a40</id>
    <report_name>#VMI Sale (Retail) Register#</report_name>
    <folder_name>Inventory\Register\Vendor Managed Inventory (VMI)</folder_name>
    <folder_id>ae4a9be4-3719-4780-b0dc-beb34b981993</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>1</output_mode>
    <prevent_output>3</prevent_output>
    <page_size>A4</page_size>
    <page_orientation>Landscape</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will display Sale (Retail) of the item(s) of the selected Vendor for last 60 days				
</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_RETAIL_SALE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>06-Retail|*{*}*|02-Transaction</category>
  </entity>
  <entity>
    <entity_name>LV_VENDOR_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>1577477225</id>
    <cell_text>=@OrgName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1269958344</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1868781010</id>
    <cell_text>=Bold(''As On '')&amp;GlobalDateFormat(Today())&amp;bold('' for last '')&amp;''60''&amp;Bold('' days'')</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1955739155</id>
    <cell_text>=bold(''Vendor Name: '')&amp;@VendorItemName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>20</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>622441245</id>
    <cell_text>Site Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>368284383</id>
    <cell_text>Sale Date</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1451229775</id>
    <cell_text>Division</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>362644866</id>
    <cell_text>Section</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1674188350</id>
    <cell_text>Department</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1610444124</id>
    <cell_text>CAT1</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1990660322</id>
    <cell_text>CAT2</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2022607772</id>
    <cell_text>CAT3</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>593668588</id>
    <cell_text>CAT4</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>566820813</id>
    <cell_text>CAT5</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1102520</id>
    <cell_text>CAT6</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1105923389</id>
    <cell_text>Barcode</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>494983242</id>
    <cell_text>Item Code</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1430875528</id>
    <cell_text>RSP</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>430994767</id>
    <cell_text>Qty.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>2024137417</id>
    <cell_text>Gross Amt.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>238523116</id>
    <cell_text>Disc. Amt.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>16</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1665166982</id>
    <cell_text>Net Amt.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1126210154</id>
    <cell_text>Tax(%)</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>18</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>738342337</id>
    <cell_text>Tax Amt.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1759250184</id>
    <cell_text>=bold(''Vendor Name: '')&amp;{LV_VENDOR_ITEM_01.name}&amp;''[''&amp;{LV_VENDOR_ITEM_01.identity_no}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>7</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>15</font_size>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1778998282</id>
    <cell_text>={LV_SITE_01.name}&amp;'' [''&amp;{LV_SITE_01.short_code}&amp;'']''</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>92716134</id>
    <cell_text>LV_RETAIL_SALE_01.csdate</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>689235088</id>
    <cell_text>LV_ITEM_01.division</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1346149994</id>
    <cell_text>LV_ITEM_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1605305082</id>
    <cell_text>LV_ITEM_01.department</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>424029519</id>
    <cell_text>LV_ITEM_01.category1</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>919005144</id>
    <cell_text>LV_ITEM_01.category2</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1698911163</id>
    <cell_text>LV_ITEM_01.category3</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>279868277</id>
    <cell_text>LV_ITEM_01.category4</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>8</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>162755780</id>
    <cell_text>LV_ITEM_01.category5</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>9</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>878431906</id>
    <cell_text>LV_ITEM_01.category6</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>10</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1189318840</id>
    <cell_text>LV_ITEM_01.barcode</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>11</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1113500675</id>
    <cell_text>LV_ITEM_01.item_code</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>12</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>402676040</id>
    <cell_text>LV_RETAIL_SALE_01.rsp</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>13</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1399604301</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.qty})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1592328560</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.grsamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>608556903</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.discount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>16</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1288245781</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.netamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1546717506</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.taxpercent})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>18</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>2103913937</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.taxamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>785508826</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>2095988151</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1166065989</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>645334982</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1004534464</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1072122900</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>94635876</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1917867075</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1318331487</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>8</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1326834630</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>9</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1566292115</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>10</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1491500518</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>11</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1555941410</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>12</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>19791511</id>
    <cell_text>Total:</cell_text>
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>13</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1147561382</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.qty})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>14</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>419724794</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.grsamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>15</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1908883433</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.discount})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>16</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1710721460</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.netamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1866343250</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>8</cell_row>
    <cell_col>18</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1359319814</id>
    <cell_text>=AggSum({LV_RETAIL_SALE_01.taxamt})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>19</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
  </cell>
  <cell>
    <id>1162968298</id>
    <cell_text>=''Print Date: ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>531572438</id>
    <cell_text>As On date based on Sale Date.</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>2</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>15</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
    <foreground_color>#0000FF</foreground_color>
  </cell>
  <cell>
    <id>1315746473</id>
    <cell_text>=''Page No.: ''&amp;@pageNumber@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>9</cell_row>
    <cell_col>17</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_ITEM_01.vendor</group_field>
  </row>
  <row>
    <group_type>Detail</group_type>
    <suppress_flag>True</suppress_flag>
    <shading>
      <color>#FFFFFF</color>
    </shading>
    <shading>
      <color>#E2E2E2</color>
    </shading>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.item_code</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.vendor</group_field>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>198</column_width>
  </column>
  <column>
    <column_width>71</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>55</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_RETAIL_SALE_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_RETAIL_SALE_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_RETAIL_SALE_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_RETAIL_SALE_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_VENDOR_ITEM_01</entity_from_name>
    <entity_to_name>LV_ITEM_01</entity_to_name>
    <entity_from_id>LV_VENDOR_ITEM_01</entity_from_id>
    <entity_to_id>LV_ITEM_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>vendor_code</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>vendor_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_ITEM_01.vendor</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_SITE_01.name</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_RETAIL_SALE_01.csdate</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.item_code</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_RETAIL_SALE_01.csdate</filter_name>
    <order_num>0</order_num>
    <operator>bt</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>867365116</filter_ref_id>
    <filter_title>Period (Days)</filter_title>
    <values>
      <value>=TodayMinus60Days()</value>
    </values>
    <values>
      <value>=Today()</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_VENDOR_ITEM_01.code</filter_name>
    <order_num>1</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>762331669</filter_ref_id>
    <filter_title />
    <values>
      <value>@VendorItemName@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2020-04-17 17:11:33', '1141', '2026-06-16 08:28:30.766687',
    '132560', '75a16cac-c843-4b39-8259-a06b6f97fea3', 27,
    FALSE, 2, 768,
    NULL, 16, 0,
    FALSE, FALSE, NULL,
    NULL, '2026004', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '018545b0-2b8a-4826-bdd2-fb07a6732a40', '56e983e1-ba23-4c38-b8ce-ec8b83d234a5', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026004', 'U'
);
