-- =====================================================
-- INSERT statement for content_id: 8322675f-1646-4257-93f6-487606f94ac8
-- Name: #Inventory Status Summary#
-- Action: UPDATE
-- Version: 2026004
-- Generated on: 2026-07-08 16:26:14
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '8322675f-1646-4257-93f6-487606f94ac8', 0, 0,
    NULL, '#Inventory Status Summary#', 'This report will show the Site and Stockpoint wise inventory status summary.',
    '<report>
  <main>
    <id>8322675f-1646-4257-93f6-487606f94ac8</id>
    <report_name>#Inventory Status Summary#</report_name>
    <folder_name>Inventory\Status</folder_name>
    <folder_id>2d9354a7-390e-4346-96db-7deb71635fa1</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will show the Site and Stockpoint wise inventory status summary.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <show_html_toolbar>Always</show_html_toolbar>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>TV_INV_STATUS_SUMMARY_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|04-Report Specific</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_BATCHSERIAL_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_STOCKPOINT_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>2061943995</id>
    <cell_text>=@ExecutingSQL@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>334242129</id>
    <cell_text>=@IsCategory1@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1204062448</id>
    <cell_text>=@IsCategory2@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>213064113</id>
    <cell_text>=@IsCategory3@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1189483290</id>
    <cell_text>=@IsCategory4@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1871942730</id>
    <cell_text>=@IsCategory5@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>959897888</id>
    <cell_text>=@IsCategory6@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>665241313</id>
    <cell_text>=@IsBarcodeApplicable@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>925108813</id>
    <cell_text>=@ConnOUName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>223677860</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>919565452</id>
    <cell_text>=Bold(''Ason: '')&amp;@ASON@&amp;Bold('' Division:- '')&amp;@Division@&amp;Bold('' Section:- '')&amp;@Section@&amp;Bold('' Department:- '')&amp;@Department@&amp;Bold('' Site Type: '')&amp;@SiteTypeDesc@&amp;bold('' Site Name: '')&amp;@SiteTypeDescSiteName@&amp;Bold('' Location Group: '')&amp;@LocationGroupCode@&amp;Bold('' Stock Point : '')&amp;@GroupCodeWiseStockPoint@&amp;Bold('' MRP From: '')&amp;@MRPFrom@&amp;Bold('' MRP To: '')&amp;@MRPTo@&amp;Bold('' Location Wise: '')&amp;@LocationWise@&amp;Bold('' Show Batch/Serial : '')&amp;@ShowBatchSerial@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1758416993</id>
    <crosstab>True</crosstab>
    <crosstab_id>232832083</crosstab_id>
    <cell_text>Site</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#528AB2</background_color>
  </cell>
  <cell>
    <id>29758675</id>
    <crosstab>True</crosstab>
    <cell_text>Item Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#528AB2</background_color>
  </cell>
  <cell>
    <id>178623150</id>
    <crosstab>True</crosstab>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#528AB2</background_color>
  </cell>
  <cell>
    <id>1768577159</id>
    <crosstab>True</crosstab>
    <cell_text>Stock Point</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#528AB2</background_color>
  </cell>
  <cell>
    <id>559065529</id>
    <crosstab>True</crosstab>
    <cell_text>LV_STOCKPOINT_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#528AB2</background_color>
  </cell>
  <cell>
    <id>626597939</id>
    <crosstab>True</crosstab>
    <cell_text>Grand Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>12</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#396381</background_color>
  </cell>
  <cell>
    <id>2110844596</id>
    <crosstab>True</crosstab>
    <cell_text>={LV_SITE_01.short_code}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>57428079</id>
    <crosstab>True</crosstab>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_italic_flag>True</font_italic_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#A5C8E2</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1470824810</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <font_italic_flag>True</font_italic_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#396381</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1093629302</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <font_italic_flag>True</font_italic_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#396381</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>1721057802</id>
    <crosstab>True</crosstab>
    <cell_text>={LV_ITEM_01.item_name}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#FFFFFF</background_color>
  </cell>
  <cell>
    <id>769419227</id>
    <crosstab>True</crosstab>
    <cell_text>LV_ITEM_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
  </cell>
  <cell>
    <id>775366556</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <foreground_color>#000000</foreground_color>
    <background_color>#D2E3F0</background_color>
  </cell>
  <cell>
    <id>1800489318</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_italic_flag>True</font_italic_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#7BA6C4</background_color>
  </cell>
  <cell>
    <id>1464729036</id>
    <crosstab>True</crosstab>
    <cell_text>Total :</cell_text>
    <cell_type>text</cell_type>
    <cell_row>9</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>12</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_left_color>#A5C8E2</border_left_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#396381</background_color>
  </cell>
  <cell>
    <id>2121857266</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#396381</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#7BA6C4</background_color>
  </cell>
  <cell>
    <id>1657743613</id>
    <crosstab>True</crosstab>
    <cell_text>TV_INV_STATUS_SUMMARY_01.closing_stock</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#396381</border_top_color>
    <border_bottom_color>#A5C8E2</border_bottom_color>
    <border_right_color>#A5C8E2</border_right_color>
    <background_color>#7BA6C4</background_color>
  </cell>
  <cell>
    <id>618216708</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>591471694</id>
    <cell_text>=''Page : ''&amp;@pageNumber@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>10</cell_row>
    <cell_col>2</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>116</column_width>
  </column>
  <column>
    <column_width>164</column_width>
  </column>
  <column>
    <column_width>46</column_width>
  </column>
  <column>
    <column_width>77</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>TV_INV_STATUS_SUMMARY_01</entity_from_name>
    <entity_to_name>LV_ITEM_BATCHSERIAL_01</entity_to_name>
    <entity_from_id>TV_INV_STATUS_SUMMARY_01</entity_from_id>
    <entity_to_id>LV_ITEM_BATCHSERIAL_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>invbatch_serial_code</col_from_name>
      <col_to_name>batch_serial_code</col_to_name>
    </key>
    <clause>
      <left_side>invbatch_serial_code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>batch_serial_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>TV_INV_STATUS_SUMMARY_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>TV_INV_STATUS_SUMMARY_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>TV_INV_STATUS_SUMMARY_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>TV_INV_STATUS_SUMMARY_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_STOCKPOINT_01</entity_from_name>
    <entity_to_name>TV_INV_STATUS_SUMMARY_01</entity_to_name>
    <entity_from_id>LV_STOCKPOINT_01</entity_from_id>
    <entity_to_id>TV_INV_STATUS_SUMMARY_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>loccode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>loccode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_SITE_01.name</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.item_name</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STOCKPOINT_01.name</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>TV_INV_STATUS_SUMMARY_01.closing_stock</filter_name>
    <order_num>0</order_num>
    <operator>&gt;</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>73929580</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.vendor</filter_name>
    <order_num>1</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1443610013</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category1</filter_name>
    <order_num>2</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1021195703</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category2</filter_name>
    <order_num>3</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1879697145</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category3</filter_name>
    <order_num>4</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>515205354</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category4</filter_name>
    <order_num>5</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>596784843</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category5</filter_name>
    <order_num>6</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>2124135263</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category6</filter_name>
    <order_num>7</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>383600751</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.barcode</filter_name>
    <order_num>8</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>739272467</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.mrp</filter_name>
    <order_num>9</order_num>
    <operator>&gt;=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1233036198</filter_ref_id>
    <filter_title />
    <values>
      <value>@MRPFrom@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.mrp</filter_name>
    <order_num>10</order_num>
    <operator>&lt;=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>372653217</filter_ref_id>
    <filter_title />
    <values>
      <value>@MRPTo@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.division</filter_name>
    <order_num>11</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>2113918215</filter_ref_id>
    <filter_title />
    <values>
      <value>@Division@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.section</filter_name>
    <order_num>12</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>629670780</filter_ref_id>
    <filter_title />
    <values>
      <value>@Section@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.department</filter_name>
    <order_num>13</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1171802799</filter_ref_id>
    <filter_title />
    <values>
      <value>@Department@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <crosstab>
    <id>232832083</id>
    <header_per_page>true</header_per_page>
    <row_header_placement>Column</row_header_placement>
    <row_header>
      <id>1042330820</id>
      <source>2110844596</source>
      <label>1758416993</label>
      <total>57428079</total>
      <total_placement>Top</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>406251602</id>
      <source>1721057802</source>
      <label>29758675</label>
      <total>0</total>
      <total_placement>None</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>692992620</id>
      <source>769419227</source>
      <label>178623150</label>
      <total>1464729036</total>
      <total_placement>Bottom</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <col_header>
      <id>177725984</id>
      <source>559065529</source>
      <label>1768577159</label>
      <total>626597939</total>
      <total_placement>Right</total_placement>
      <sort_method>None</sort_method>
    </col_header>
    <tabulation>
      <source>775366556</source>
      <method>Sum</method>
      <value>Aggregate</value>
      <label>0</label>
      <tabstyle>
        <rowhdr>406251602</rowhdr>
        <style>1470824810</style>
      </tabstyle>
      <tabstyle>
        <colhdr>177725984</colhdr>
        <style>1800489318</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>406251602</rowhdr>
        <colhdr>177725984</colhdr>
        <style>1093629302</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>1042330820</rowhdr>
        <style>2121857266</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>1042330820</rowhdr>
        <colhdr>177725984</colhdr>
        <style>1657743613</style>
      </tabstyle>
    </tabulation>
  </crosstab>
  <serverevent>
    <event_type>OnExecuteSqlStatementConstructed</event_type>
    <event_id>0</event_id>
  </serverevent>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2020-02-07 17:46:39', '1295', '2026-04-06 12:07:50.509437',
    '132560', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026004', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '8322675f-1646-4257-93f6-487606f94ac8', '6d0a3125-672a-4b60-a548-1c3be854e5b8', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026004', 'U'
);
