-- =====================================================
-- INSERT statement for content_id: 929901ae-97b1-486e-b938-280ff980e0f9
-- Name: #Stock Adjustment Summary#
-- Action: UPDATE
-- Version: 2026004
-- Generated on: 2026-07-08 16:26:16
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    '929901ae-97b1-486e-b938-280ff980e0f9', 0, 0,
    NULL, '#Stock Adjustment Summary#', 'This report will show the Summary of physical stock audit adjustments passed during the process of Stock audit plan update.',
    '<report>
  <main>
    <id>929901ae-97b1-486e-b938-280ff980e0f9</id>
    <report_name>#Stock Adjustment Summary#</report_name>
    <folder_name>Inventory\Register</folder_name>
    <folder_id>c55b7299-0a15-4662-bb70-cdc244f1c79d</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>Letter</page_size>
    <page_orientation>Portrait</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will show the Summary of physical stock audit adjustments passed during the process of Stock audit plan update.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_ITEM_BATCHSERIAL_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>03-Inventory|*{*}*|02-Transaction</category>
  </entity>
  <entity>
    <entity_name>LV_STOCKPOINT_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>56716229</id>
    <cell_text>@ExecutingSQL@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>791605510</id>
    <cell_text>=@IsCategory1@&amp;'' ''&amp;@IsCategory2@&amp;'' ''&amp;@IsCategory3@&amp;'' ''&amp;@IsCategory4@&amp;'' ''&amp;@IsCategory5@&amp;'' ''&amp;@IsCategory6@&amp;'' ''&amp;@IsBarcodeApplicable@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>847189994</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>2</cell_row>
    <cell_col>1</cell_col>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1543760581</id>
    <cell_text>=@ConnOUName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>861118807</id>
    <cell_text>@reportName@</cell_text>
    <cell_type>text</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>175561633</id>
    <cell_text>=Bold(''From Date : '')&amp;Italic(GlobalDateFormat(@DTFR@))&amp;Bold('' To : '')&amp;Italic(GlobalDateFormat(@DTTO@))&amp;Bold('' Division : '')&amp;Italic(If(Len(@Division@)=0, ''All'', @Division@))&amp;Bold('' Section : '')&amp;Italic(If(Len(@Section@)=0,''All'',@Section@))&amp;Bold('' Department : '')&amp;Italic(If(Len(@Department@)=0,''All'',@Department@))&amp;Bold('' Stock Point : '')&amp;Italic(If(Len(@WarehouseStockPoint@)=0,''All'',@WarehouseStockPoint@))&amp;Bold('' Site : '')&amp;Italic(If(Len(@OrgSiteName@)=0,''All'',@OrgSiteName@))&amp;Bold('' Show Batch/Serial : '')&amp;@ShowBatchSerial@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>9</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1674948752</id>
    <cell_text>Stock Point</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>562968397</id>
    <cell_text>Division</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>880539991</id>
    <cell_text>Section</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>997130920</id>
    <cell_text>Department</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1372005880</id>
    <cell_text>Adjusted Quantity</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1233275407</id>
    <cell_text>Book Quantity</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>352153048</id>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1366135106</id>
    <cell_text>Rate</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1277258102</id>
    <cell_text>Amount</cell_text>
    <cell_type>text</cell_type>
    <cell_row>6</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>386130911</id>
    <cell_text>=''Source Site : ''&amp;{LV_STKAUDIT_ADJUSTMENT_BATCH_01.owner_site}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>15031683</id>
    <cell_text>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stock_point_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>8</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1300823932</id>
    <cell_text>LV_STKAUDIT_ADJUSTMENT_BATCH_01.devision</cell_text>
    <cell_type>data</cell_type>
    <cell_row>9</cell_row>
    <cell_col>1</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>308914532</id>
    <cell_text>LV_STKAUDIT_ADJUSTMENT_BATCH_01.section</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>2</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>607894450</id>
    <cell_text>LV_STKAUDIT_ADJUSTMENT_BATCH_01.department</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>1388503237</id>
    <cell_text>LV_ITEM_01.item_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>3</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Text</format_type>
  </cell>
  <cell>
    <id>471191188</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>765816852</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1098717356</id>
    <cell_text>LV_ITEM_01.uom</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1651037650</id>
    <cell_text>=If(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})=0,0,[I13]/AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>1098719906</id>
    <cell_text>=AggSum( {LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}* {LV_ITEM_01.standard_rate})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>12</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>120668795</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1130241796</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>957119152</id>
    <cell_text>=AggSum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>13</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1588439390</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1791176931</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2135350248</id>
    <cell_text>=AggSum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1544640096</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>417574668</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>15</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>775485565</id>
    <cell_text>Stock Point Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>688348647</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>329826558</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>153178355</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1337185194</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>17</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1589342344</id>
    <cell_text>=AggSum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>17</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>450912699</id>
    <cell_text>Site Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>32903984</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1886676422</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1563778056</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>2024740964</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>19</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1399794985</id>
    <cell_text>=AggSum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>19</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1908459816</id>
    <cell_text>Grand Total</cell_text>
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1433512219</id>
    <cell_text>=AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1516368075</id>
    <cell_text>=Abs(AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.physical_stock_quantity})-AggSum({LV_STKAUDIT_ADJUSTMENT_BATCH_01.quantity}))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>394961431</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>6</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1969155518</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>21</cell_row>
    <cell_col>7</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>978177971</id>
    <cell_text>=AggSum([I13])</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>21</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_vertical_align>Top</cell_vertical_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1220842510</id>
    <cell_text>*Cost based on FIFO</cell_text>
    <cell_type>text</cell_type>
    <cell_row>22</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>169116240</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>23</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>568790822</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1446234339</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>438808806</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>793718487</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>1834985639</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>23</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <cell>
    <id>804993461</id>
    <cell_text>=''Page No :''&amp;PageNumber()</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>23</cell_row>
    <cell_col>8</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_top_width>1</border_top_width>
    <border_top_color>#000000</border_top_color>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.owner_site</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stock_point_name</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.devision</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.section</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.department</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_ITEM_01.item_name</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.department</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.section</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.devision</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stock_point_name</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stock_point_name</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.owner_site</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_STKAUDIT_ADJUSTMENT_BATCH_01.owner_site</group_field>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>62</column_width>
  </column>
  <column>
    <column_width>48</column_width>
  </column>
  <column>
    <column_width>46</column_width>
  </column>
  <column>
    <column_width>269</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>51</column_width>
  </column>
  <column>
    <column_width>76</column_width>
  </column>
  <column>
    <column_width>85</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_01</entity_from_name>
    <entity_to_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_to_name>
    <entity_from_id>LV_ITEM_01</entity_from_id>
    <entity_to_id>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_from_name>
    <entity_to_name>LV_ITEM_BATCHSERIAL_01</entity_to_name>
    <entity_from_id>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_from_id>
    <entity_to_id>LV_ITEM_BATCHSERIAL_01</entity_to_id>
    <join_type>leftouter</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>invbatch_serial_code</col_from_name>
      <col_to_name>batch_serial_code</col_to_name>
    </key>
    <clause>
      <left_side>invbatch_serial_code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>batch_serial_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_STOCKPOINT_01</entity_from_name>
    <entity_to_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_to_name>
    <entity_from_id>LV_STOCKPOINT_01</entity_from_id>
    <entity_to_id>LV_STKAUDIT_ADJUSTMENT_BATCH_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>loccode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>loccode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.owner_site</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stock_point_name</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.devision</sort_name>
    <sort_title />
    <order_num>2</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.section</sort_name>
    <sort_title />
    <order_num>3</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.department</sort_name>
    <sort_title />
    <order_num>4</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_ITEM_01.item_name</sort_name>
    <sort_title />
    <order_num>5</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_ITEM_01.category1</filter_name>
    <order_num>0</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1047773818</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category2</filter_name>
    <order_num>1</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>980963781</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category3</filter_name>
    <order_num>2</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>2016617354</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category4</filter_name>
    <order_num>3</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1679607186</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category5</filter_name>
    <order_num>4</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>988492703</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_01.category6</filter_name>
    <order_num>5</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1151198402</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.icode</filter_name>
    <order_num>6</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1726569167</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.admou_code</filter_name>
    <order_num>7</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1002971798</filter_ref_id>
    <filter_title />
    <values>
      <value>@ConnOUCode@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STOCKPOINT_01.code</filter_name>
    <order_num>8</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>534078692</filter_ref_id>
    <filter_title />
    <values>
      <value>@WarehouseStockPoint@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.stkadjdt</filter_name>
    <order_num>9</order_num>
    <operator>bt</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1020164754</filter_ref_id>
    <filter_title />
    <values>
      <value>@DTFR@</value>
    </values>
    <values>
      <value>@DTTO@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.devision</filter_name>
    <order_num>10</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1253576932</filter_ref_id>
    <filter_title />
    <values>
      <value>@Division@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.section</filter_name>
    <order_num>11</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>836047282</filter_ref_id>
    <filter_title />
    <values>
      <value>@Section@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.department</filter_name>
    <order_num>12</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>862130054</filter_ref_id>
    <filter_title />
    <values>
      <value>@Department@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_STKAUDIT_ADJUSTMENT_BATCH_01.admsite_code</filter_name>
    <order_num>13</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1216516581</filter_ref_id>
    <filter_title />
    <values>
      <value>@OrgSiteName@</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <serverevent>
    <event_type>OnExecuteSqlStatementConstructed</event_type>
    <event_id>0</event_id>
  </serverevent>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2019-08-26 15:29:19', '2109', '2026-05-05 11:41:43.177571',
    '132562', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026004', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    '929901ae-97b1-486e-b938-280ff980e0f9', '8ee7e5fe-12b9-4212-951a-82008c8603d0', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026004', 'U'
);
