-- =====================================================
-- INSERT statement for content_id: a96e3d4b-b2ef-4495-8403-c139cae9cfa9
-- Name: #Assembly Order Status (Summary)#
-- Action: UPDATE
-- Version: 2026004
-- Generated on: 2026-07-08 16:26:15
-- =====================================================

-- Insert into ex_content_dev
INSERT INTO ginview.ex_content_dev (
    content_id, content_type, report_type, content_attribute, "name",
    description, text_content, bit_content, deleted_flag, created_date,
    created_by, modified_date, modified_by, owner_id, exports_allowed,
    inherit_flag, default_party_type_id, default_access_flags, extended_attributes,
    default_export_type, report_tree_shortcut_action, use_cache_execution,
    is_cache_valid, associated_reports, reportfoldercode, release_version, action
)
VALUES (
    'a96e3d4b-b2ef-4495-8403-c139cae9cfa9', 0, 0,
    NULL, '#Assembly Order Status (Summary)#', 'This report will show the Item count summary for each Process as on selected date. This is a Cross Tab report.',
    '<report>
  <main>
    <id>a96e3d4b-b2ef-4495-8403-c139cae9cfa9</id>
    <report_name>#Assembly Order Status (Summary)#</report_name>
    <folder_name>Production\Register</folder_name>
    <folder_id>f405dfdf-5ef8-4ec2-96fb-3bf2e90f3232</folder_id>
    <version>1</version>
    <type>Standard</type>
    <sql_stmt />
    <show_execute_form>False</show_execute_form>
    <filter_execution_window>Default</filter_execution_window>
    <fit_page_width>False</fit_page_width>
    <suppress_formatting>False</suppress_formatting>
    <report_tree_shortcut>0</report_tree_shortcut>
    <output_mode>6</output_mode>
    <prevent_output />
    <page_size>A4</page_size>
    <page_orientation>Landscape</page_orientation>
    <include_setup_info>No</include_setup_info>
    <description>This report will show the Item count summary for each Process as on selected date. This is a Cross Tab report.</description>
    <filter_description />
    <show_grid>False</show_grid>
    <pdf_template />
    <embedded_pdf_template />
    <simulate_pdf>False</simulate_pdf>
    <no_data_render_type>ShowReport</no_data_render_type>
    <show_interactive_sorts>True</show_interactive_sorts>
    <allow_column_hide>True</allow_column_hide>
    <display_report_column_headers>Default</display_report_column_headers>
    <groups_on_separate_worksheets>False</groups_on_separate_worksheets>
    <enable_cartesian_processing>Default</enable_cartesian_processing>
    <visualization_report>false</visualization_report>
    <use_cache_execution>false</use_cache_execution>
    <show_html_toolbar>Always</show_html_toolbar>
    <excel_freeze_rows>1</excel_freeze_rows>
    <excel_freeze_columns>1</excel_freeze_columns>
    <excel_show_gridlines>True</excel_show_gridlines>
    <suppressfiltersinterface>False</suppressfiltersinterface>
    <suppresssortsinterface>False</suppresssortsinterface>
    <row_range_limit>0</row_range_limit>
  </main>
  <entity>
    <entity_name>LV_ITEM_03</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master|*{*}*|Production|*{*}*|Item</category>
  </entity>
  <entity>
    <entity_name>LV_CUSTOMER_SUPPLIER_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <entity>
    <entity_name>LV_PRD_JOB_ORDER_DETAIL_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>07-Production|*{*}*|02-Transaction|*{*}*|Job Order</category>
  </entity>
  <entity>
    <entity_name>LV_PRD_JOB_ORDER_HEADER_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>07-Production|*{*}*|02-Transaction|*{*}*|Job Order</category>
  </entity>
  <entity>
    <entity_name>LV_SITE_01</entity_name>
    <group_by_flag>False</group_by_flag>
    <category>01-Master</category>
  </entity>
  <cell>
    <id>1344914191</id>
    <cell_text>=@IsBarcodeApplicable@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1568408429</id>
    <cell_text>=@IsCategory1@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>55801224</id>
    <cell_text>=@IsCategory2@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1578918651</id>
    <cell_text>=@IsCategory3@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>398192642</id>
    <cell_text>=@IsCategory4@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>4</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>990880226</id>
    <cell_text>=@IsCategory5@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>32248615</id>
    <cell_text>=@Division@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>6</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>2064090379</id>
    <cell_text>=@Section@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>0</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>325340292</id>
    <cell_text>=@OrgSiteName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>777468435</id>
    <cell_text>=@IsCategory6@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>5</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>79220617</id>
    <cell_text>=@Department@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>1</cell_row>
    <cell_col>7</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>1589515073</id>
    <cell_text>=@ConnOUName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>2</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>13</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1684167742</id>
    <cell_text>=@reportName@</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>3</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>11</font_size>
    <font_bold_flag>True</font_bold_flag>
  </cell>
  <cell>
    <id>1322318548</id>
    <cell_text>=Concatenate(Bold('' Order upto date : ''),@ASON@,Bold('' Site Name: ''),@OrgSiteName@,Bold('' Process Name: ''),@Process@,Bold('' Jobber : ''),@VendorName@,Bold('' Divison : ''), If(@Division@=DbNull(), ''ALL'', @Division@), Bold('' Section : ''), If(Len(@Section@)=0, ''ALL'', @Section@), Bold('' Department : ''), If(Len(@Department@)=0, ''ALL'', @Department@))</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>4</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <cell>
    <id>665731556</id>
    <cell_text>Site Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1712389749</id>
    <cell_text>Process Name</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1353762408</id>
    <cell_text>Pending Qty</cell_text>
    <cell_type>text</cell_type>
    <cell_row>5</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>195106085</id>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>6</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>8</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>302576405</id>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>7</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>4</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>937511695</id>
    <cell_text>LV_PRD_JOB_ORDER_HEADER_01.process_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>7</cell_row>
    <cell_col>4</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>2131784290</id>
    <cell_text>=[H9]</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>7</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>859149035</id>
    <cell_text>=aggsum({LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity})</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>8</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
  </cell>
  <cell>
    <id>839933005</id>
    <crosstab>True</crosstab>
    <crosstab_id>1363476174</crosstab_id>
    <cell_text>Site</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>0</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>70863601</id>
    <crosstab>True</crosstab>
    <cell_text>Jobber</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1365003134</id>
    <crosstab>True</crosstab>
    <cell_text>ITEM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>226877266</id>
    <crosstab>True</crosstab>
    <cell_text>SAItem</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1118281760</id>
    <crosstab>True</crosstab>
    <cell_text>UOM</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>188242095</id>
    <crosstab>True</crosstab>
    <cell_text />
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>5</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1641075177</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_HEADER_01.process_name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>10</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1562731465</id>
    <crosstab>True</crosstab>
    <cell_text>Grand Total :-</cell_text>
    <cell_type>text</cell_type>
    <cell_row>10</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_top_width>1</border_top_width>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_top_color>#000000</border_top_color>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
    <background_color>#E2E2E2</background_color>
  </cell>
  <cell>
    <id>1213076181</id>
    <crosstab>True</crosstab>
    <cell_text>LV_SITE_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>0</cell_col>
    <cell_vertical_align>Top</cell_vertical_align>
    <cell_rowspan>2</cell_rowspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1214759953</id>
    <crosstab>True</crosstab>
    <cell_text>LV_CUSTOMER_SUPPLIER_01.name</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>1</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>798709707</id>
    <crosstab>True</crosstab>
    <cell_text>={LV_ITEM_03.item_name}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>2</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <format_type>Text</format_type>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1929251807</id>
    <crosstab>True</crosstab>
    <cell_text>={LV_PRD_JOB_ORDER_DETAIL_01.sub_assembly_item}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>3</cell_col>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>148013133</id>
    <crosstab>True</crosstab>
    <cell_text>={LV_ITEM_03.uom}</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>11</cell_row>
    <cell_col>4</cell_col>
    <cell_horizontal_align>Center</cell_horizontal_align>
    <cell_colspan>2</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1869784527</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>67483982</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>11</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1909590693</id>
    <crosstab>True</crosstab>
    <cell_text>Site Wise Total:-</cell_text>
    <cell_type>text</cell_type>
    <cell_row>12</cell_row>
    <cell_col>1</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>299202775</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>1171048065</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>12</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>297470634</id>
    <crosstab>True</crosstab>
    <cell_text>Grand Total :-</cell_text>
    <cell_type>text</cell_type>
    <cell_row>13</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>6</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>10</font_size>
    <font_bold_flag>True</font_bold_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_left_width>1</border_left_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_left_color>#000000</border_left_color>
  </cell>
  <cell>
    <id>2099942090</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>6</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>599310886</id>
    <crosstab>True</crosstab>
    <cell_text>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</cell_text>
    <cell_type>data</cell_type>
    <cell_row>13</cell_row>
    <cell_col>7</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <font_bold_flag>True</font_bold_flag>
    <format_type>Number</format_type>
    <format_decimal_places>3</format_decimal_places>
    <format_separator_flag>False</format_separator_flag>
    <format_negative_symbol_flag>True</format_negative_symbol_flag>
    <border_bottom_width>1</border_bottom_width>
    <border_right_width>1</border_right_width>
    <border_bottom_color>#000000</border_bottom_color>
    <border_right_color>#000000</border_right_color>
  </cell>
  <cell>
    <id>184761144</id>
    <cell_text>=''Print Date : ''&amp;GlobalDateFormat(Now())</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>0</cell_col>
    <cell_colspan>3</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
    <format_type>Date</format_type>
    <format_date_time>DD-MM-YYYY</format_date_time>
  </cell>
  <cell>
    <id>759690474</id>
    <cell_text>=''Page :  ''&amp;PageNumber()</cell_text>
    <cell_type>formula</cell_type>
    <cell_row>14</cell_row>
    <cell_col>3</cell_col>
    <cell_horizontal_align>Right</cell_horizontal_align>
    <cell_colspan>5</cell_colspan>
    <wrap_text_flag>True</wrap_text_flag>
    <font_name>Calibri</font_name>
    <font_size>9</font_size>
  </cell>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Page Header</group_type>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_SITE_01.name</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_SITE_01.name</group_field>
  </row>
  <row>
    <group_type>Header</group_type>
    <group_field>LV_PRD_JOB_ORDER_HEADER_01.process_name</group_field>
  </row>
  <row>
    <group_type>Footer</group_type>
    <group_field>LV_PRD_JOB_ORDER_HEADER_01.process_name</group_field>
    <suppress_flag>True</suppress_flag>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Report Footer</group_type>
  </row>
  <row>
    <group_type>Page Footer</group_type>
  </row>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>180</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>54</column_width>
  </column>
  <column>
    <column_width>52</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <column>
    <column_width>100</column_width>
  </column>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_PRD_JOB_ORDER_HEADER_01</entity_from_name>
    <entity_to_name>LV_PRD_JOB_ORDER_DETAIL_01</entity_to_name>
    <entity_from_id>LV_PRD_JOB_ORDER_HEADER_01</entity_from_id>
    <entity_to_id>LV_PRD_JOB_ORDER_DETAIL_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>1M</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>jobcode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>jobcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_CUSTOMER_SUPPLIER_01</entity_from_name>
    <entity_to_name>LV_PRD_JOB_ORDER_HEADER_01</entity_to_name>
    <entity_from_id>LV_CUSTOMER_SUPPLIER_01</entity_from_id>
    <entity_to_id>LV_PRD_JOB_ORDER_HEADER_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>pcode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>pcode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_SITE_01</entity_from_name>
    <entity_to_name>LV_PRD_JOB_ORDER_HEADER_01</entity_to_name>
    <entity_from_id>LV_SITE_01</entity_from_id>
    <entity_to_id>LV_PRD_JOB_ORDER_HEADER_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>sitecode</col_from_name>
      <col_to_name>admsite_code</col_to_name>
    </key>
    <clause>
      <left_side>sitecode</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>admsite_code</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <join>
    <affinity>Global</affinity>
    <entity_from_name>LV_ITEM_03</entity_from_name>
    <entity_to_name>LV_PRD_JOB_ORDER_DETAIL_01</entity_to_name>
    <entity_from_id>LV_ITEM_03</entity_from_id>
    <entity_to_id>LV_PRD_JOB_ORDER_DETAIL_01</entity_to_id>
    <join_type>inner</join_type>
    <relation_type>11</relation_type>
    <weight>0</weight>
    <key>
      <col_from_name>code</col_from_name>
      <col_to_name>assembly_icode</col_to_name>
    </key>
    <clause>
      <left_side>code</left_side>
      <left_side_type>Column</left_side_type>
      <comparison>EQ</comparison>
      <right_side>assembly_icode</right_side>
      <right_side_type>Column</right_side_type>
      <conjunction>AND</conjunction>
      <level>0</level>
    </clause>
  </join>
  <sort>
    <sort_name>LV_SITE_01.name</sort_name>
    <sort_title />
    <order_num>0</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <sort>
    <sort_name>LV_PRD_JOB_ORDER_HEADER_01.process_name</sort_name>
    <sort_title />
    <order_num>1</order_num>
    <ascending_flag>True</ascending_flag>
  </sort>
  <filter>
    <filter_name>LV_SITE_01.sitecode</filter_name>
    <order_num>0</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>2026985745</filter_ref_id>
    <filter_title />
    <values>
      <value>@OrgSiteName@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_PRD_JOB_ORDER_HEADER_01.prcode</filter_name>
    <order_num>1</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>201243157</filter_ref_id>
    <filter_title />
    <values>
      <value>@Process@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_CUSTOMER_SUPPLIER_01.code</filter_name>
    <order_num>2</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>264083356</filter_ref_id>
    <filter_title />
    <values>
      <value>@VendorName@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_PRD_JOB_ORDER_HEADER_01.job_order_date</filter_name>
    <order_num>3</order_num>
    <operator>&lt;=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1613155908</filter_ref_id>
    <filter_title />
    <values>
      <value>@ASON@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.barcode</filter_name>
    <order_num>4</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1873810745</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category1</filter_name>
    <order_num>5</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1042511900</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category2</filter_name>
    <order_num>6</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>236558734</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category3</filter_name>
    <order_num>7</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>432258928</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category4</filter_name>
    <order_num>8</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>804437445</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category5</filter_name>
    <order_num>9</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1763794724</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.category6</filter_name>
    <order_num>10</order_num>
    <operator>=</operator>
    <prompt_flag>True</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>801440407</filter_ref_id>
    <filter_title />
    <values>
      <value />
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.division</filter_name>
    <order_num>11</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>753406525</filter_ref_id>
    <filter_title />
    <values>
      <value>@Division@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.section</filter_name>
    <order_num>12</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1060300444</filter_ref_id>
    <filter_title />
    <values>
      <value>@Section@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_ITEM_03.department</filter_name>
    <order_num>13</order_num>
    <operator>=</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>826323343</filter_ref_id>
    <filter_title />
    <values>
      <value>@Department@</value>
    </values>
  </filter>
  <filter>
    <filter_name>LV_PRD_JOB_ORDER_DETAIL_01.pending_quantity</filter_name>
    <order_num>14</order_num>
    <operator>&gt;</operator>
    <prompt_flag>False</prompt_flag>
    <and_flag>True</and_flag>
    <group_with_next_flag>False</group_with_next_flag>
    <filter_ref_id>1368381992</filter_ref_id>
    <filter_title />
    <values>
      <value>0</value>
    </values>
  </filter>
  <topn>
    <action>top</action>
    <use_topn_item>False</use_topn_item>
    <num_items>10</num_items>
    <cellId>-1</cellId>
    <direction>desc</direction>
  </topn>
  <crosstab>
    <id>1363476174</id>
    <header_per_page>true</header_per_page>
    <row_header_placement>Column</row_header_placement>
    <row_header>
      <id>1261993909</id>
      <source>1213076181</source>
      <label>839933005</label>
      <total>1909590693</total>
      <total_placement>Bottom</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>725498273</id>
      <source>1214759953</source>
      <label>70863601</label>
      <total>0</total>
      <total_placement>None</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>1187394982</id>
      <source>798709707</source>
      <label>1365003134</label>
      <total>0</total>
      <total_placement>None</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>1440565378</id>
      <source>1929251807</source>
      <label>226877266</label>
      <total>0</total>
      <total_placement>None</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <row_header>
      <id>1155754584</id>
      <source>148013133</source>
      <label>1118281760</label>
      <total>297470634</total>
      <total_placement>Bottom</total_placement>
      <sort_method>None</sort_method>
    </row_header>
    <col_header>
      <id>1384931694</id>
      <source>1641075177</source>
      <label>188242095</label>
      <total>1562731465</total>
      <total_placement>Right</total_placement>
      <sort_method>None</sort_method>
    </col_header>
    <tabulation>
      <source>1869784527</source>
      <method>Sum</method>
      <value>Aggregate</value>
      <label>0</label>
      <tabstyle>
        <rowhdr>725498273</rowhdr>
        <style>299202775</style>
      </tabstyle>
      <tabstyle>
        <colhdr>1384931694</colhdr>
        <style>67483982</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>725498273</rowhdr>
        <colhdr>1384931694</colhdr>
        <style>1171048065</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>1261993909</rowhdr>
        <style>2099942090</style>
      </tabstyle>
      <tabstyle>
        <rowhdr>1261993909</rowhdr>
        <colhdr>1384931694</colhdr>
        <style>599310886</style>
      </tabstyle>
    </tabulation>
  </crosstab>
  <serverevent>
    <event_type>OnExecuteSqlStatementConstructed</event_type>
    <event_id>0</event_id>
  </serverevent>
  <dynamicfilters />
</report>', NULL, FALSE,
    '2019-08-26 15:29:20', '2109', '2026-03-10 10:24:33.519800',
    '132562', '75a16cac-c843-4b39-8259-a06b6f97fea3', 31,
    FALSE, 2, 768,
    NULL, 0, 0,
    FALSE, FALSE, NULL,
    NULL, '2026004', 'U'
);

-- Insert into ex_content_access_dev (1 record(s))

INSERT INTO ginview.ex_content_access_dev (
    content_id, parent_id, party_type_id, party_id, sort_order,
    access_flags, child_inherits, release_version, action
)
VALUES (
    'a96e3d4b-b2ef-4495-8403-c139cae9cfa9', 'bb8f9f76-01eb-4e46-a6e0-73b877ffd168', 2,
    '75a16cac-c843-4b39-8259-a06b6f97fea3', 0, 768,
    FALSE, '2026004', 'U'
);
